;;;; SPK-07 C4: crash su buffer reali, senza I/O di produzione.
;;; REQ: REQ-VAL-001 REQ-FOR-003 REQ-FOR-004 REQ-AFF-002 REQ-AFF-007 REQ-AFF-008 REQ-AFF-009 REQ-AFF-017
(defpackage #:arcdocdb.spk07.byte-crash
  (:use #:cl)
  (:export #:check #:budget-exhausted #:exhausted-limit))
(in-package #:arcdocdb.spk07.byte-crash)
(declaim (optimize (safety 3) (debug 3)))

(define-condition budget-exhausted (error)
  ((limit :initarg :limit :reader exhausted-limit)
   (used :initarg :used :reader exhausted-used)
   (maximum :initarg :maximum :reader exhausted-maximum)
   (context :initarg :context :reader exhausted-context))
  (:report (lambda (c s)
             (format s "Budget ~S esaurito: ~S, massimo ~S."
                     (exhausted-limit c) (exhausted-used c) (exhausted-maximum c)))))
(define-condition read-interrupted (error)
  ((index :initarg :index :reader interruption-index)
   (label :initarg :label :reader interruption-label)))
(define-condition oracle-violation (error)
  ((reason :initarg :reason :reader violation-reason)
   (context :initarg :context :reader violation-context))
  (:report (lambda (c s)
             (format s "Oracle ~S: ~S" (violation-reason c) (violation-context c)))))

(defstruct meter (cases 0) (recoveries 0) (checkpoints 0)
  (interruptions 0) (restarts 0) (maximum-steps 0))
(defvar *meter*)
(defvar *limits*)
(defvar *started*)
(defvar *plan-step* 0)
(defvar *halt-at* nil)
(defvar *active-case* nil)

;;; REQ: REQ-AFF-008 REQ-VAL-001
(defun enforce (name used maximum)
  (when (> used maximum)
    (error 'budget-exhausted :limit name :used used :maximum maximum :context *active-case*)))
(defun require-fact (truth reason &optional context)
  (unless truth
    (error 'oracle-violation :reason reason :context (list *active-case* context))))
(defun checkpoint (label)
  (enforce :step-limit (1+ *plan-step*) (getf *limits* :step-limit))
  (when (eql *halt-at* *plan-step*)
    (error 'read-interrupted :index *plan-step* :label label))
  (incf *plan-step*)
  (incf (meter-checkpoints *meter*))
  (enforce :read-limit (meter-checkpoints *meter*) (getf *limits* :read-limit)))
(defun time-budget ()
  (enforce :seconds-limit
           (/ (- (get-internal-real-time) *started*) internal-time-units-per-second)
           (getf *limits* :seconds-limit)))

;;; REQ: REQ-FOR-003
;;; Packing e CRC di fixture indipendenti: nessuna API binaria di produzione.
(defun octets (&rest values)
  (make-array (length values) :element-type '(unsigned-byte 8) :initial-contents values))
(defun zeros (size)
  (make-array size :element-type '(unsigned-byte 8) :initial-element 0))
(defun pack-le (buffer start width value)
  (dotimes (i width)
    (setf (aref buffer (+ start i)) (ldb (byte 8 (* 8 i)) value)))
  buffer)
(defun unpack-le (buffer start width)
  (loop for i below width sum (ash (aref buffer (+ start i)) (* 8 i))))
(defun bitwise-crc (buffer &optional (start 0) (end (length buffer)))
  (let ((crc #xffffffff))
    (loop for i from start below end
          do (setf crc (logxor crc (aref buffer i)))
             (dotimes (bit 8)
               (setf crc (logxor (ash crc -1) (if (oddp crc) #x82f63b78 0)))))
    (logxor crc #xffffffff)))
(defun join-bytes (pieces)
  (let ((buffer (zeros (loop for p in pieces sum (length p)))) (pos 0))
    (dolist (piece pieces)
      (replace buffer piece :start1 pos)
      (incf pos (length piece)))
    buffer))
(defun fixture-record (kind flags stamp key value)
  (let* ((body (join-bytes (list key value))) (buffer (zeros (+ 24 (length body)))))
    (pack-le buffer 4 4 (bitwise-crc body))
    (setf (aref buffer 8) kind (aref buffer 9) flags)
    (pack-le buffer 10 2 (length key))
    (pack-le buffer 12 4 (length value))
    (pack-le buffer 16 8 stamp)
    (pack-le buffer 0 4 (bitwise-crc buffer 4 24))
    (replace buffer body :start1 24)
    buffer))
(defun outcome-body (csn)
  (pack-le (zeros 8) 0 8 csn))
(defun fixture-batch (records start durable stamp file-id)
  (let* ((encoded (loop for (kind flags record-stamp key value) in records
                        collect (fixture-record kind flags record-stamp
                                                (apply #'octets key) (apply #'octets value))))
         (body (zeros 32))
         (headers (join-bytes (mapcar (lambda (b) (subseq b 0 4)) encoded))))
    (pack-le body 0 8 file-id)
    (pack-le body 8 8 (+ 64 start))
    (pack-le body 16 8 (+ 64 durable))
    (pack-le body 24 4 (length records))
    (pack-le body 28 4 (bitwise-crc headers))
    (values (join-bytes (append encoded (list (fixture-record 3 0 stamp (octets) body))))
            (+ start (loop for b in encoded sum (length b))))))

;;; REQ: REQ-FOR-004 REQ-AFF-009
;;; Le storie sono specifiche letterali, non risultati di un decoder.
(defun make-fixture (version transactional confirmed)
  (let* ((specs (if transactional
                    (list '((1 1 100 (112) (1)) (1 0 10 (97) (1)))
                          (list '(2 1 101 (112) ())
                                (list 4 0 100 nil (coerce (outcome-body 20) 'list)))
                          (list (list 4 0 101 nil (coerce (outcome-body 30) 'list))
                                '(1 1 102 (113) (4)) '(2 0 30 (97) ())))
                    '(((1 0 10 (97) (1)) (1 0 10 (98) (2)))
                      ((2 0 20 (97) ()) (1 0 20 (97) (3)))
                      ((2 0 30 (98) ()) (1 0 30 (99) (4))))))
         (histories (if transactional
                        '(nil ((10 :put (97) (1)))
                          ((10 :put (97) (1)) (20 :put (112) (1)))
                          ((10 :put (97) (1)) (20 :put (112) (1))
                           (30 :delete (112) nil) (30 :delete (97) nil)))
                        '(nil ((10 :put (97) (1)) (10 :put (98) (2)))
                          ((10 :put (97) (1)) (10 :put (98) (2))
                           (20 :delete (97) nil) (20 :put (97) (3)))
                          ((10 :put (97) (1)) (10 :put (98) (2))
                           (20 :delete (97) nil) (20 :put (97) (3))
                           (30 :delete (98) nil) (30 :put (99) (4))))))
         (file-id 31) (pos 0) (pieces nil) (batches nil)
         (frontier (loop for records in (subseq specs 0 confirmed)
                         sum (+ 56 (loop for record in records
                                        sum (+ 24 (length (fourth record)) (length (fifth record))))))))
    (loop for records in specs for stamp in '(10 20 30)
          do (multiple-value-bind (bytes seal-start)
                 (fixture-batch records pos (min pos frontier) stamp file-id)
               (push (list :start pos :seal-start seal-start :end (+ pos (length bytes))
                           :stamp stamp :durable (+ 64 (min pos frontier)) :count (length records)) batches)
               (push bytes pieces)
               (incf pos (length bytes))))
    (enforce :buffer-limit pos 512)
    (list :name (format nil "~A-v~D-F~D" (if transactional "prepared-outcome" "ordinaria") version confirmed)
          :version version :file-id file-id :file-offset 64
          :confirmed-lots confirmed :frontier frontier
          :bytes (join-bytes (reverse pieces)) :batches (reverse batches)
          :histories histories :records specs)))
(defun prefix-end (fixture count)
  (if (zerop count) 0 (getf (nth (1- count) (getf fixture :batches)) :end)))

;;; REQ: REQ-FOR-003 REQ-FOR-004 REQ-AFF-002
(defun verified-record (buffer pos end version)
  (multiple-value-bind (next kind flags stamp ks ke vs ve)
      (arcdocdb.record:verifica-record buffer pos end :version version :document-limit 512)
    (values (list :kind kind :flags flags :stamp stamp
                  :key (coerce (subseq buffer ks ke) 'list)
                  :value (coerce (subseq buffer vs ve) 'list)
                  :csn (when (= kind 4) (arcdocdb.binary:leggi-u64 buffer vs))) next)))
(defun unsafe-record (buffer pos end)
  "Mutante mirato: layout letto senza alcun CRC; non è l'oracolo positivo."
  (require-fact (<= (+ pos 24) end) :unsafe-short-header)
  (let* ((ks (+ pos 24)) (ke (+ ks (unpack-le buffer (+ pos 10) 2)))
         (next (+ ke (unpack-le buffer (+ pos 12) 4))) (kind (aref buffer (+ pos 8))))
    (require-fact (<= next end) :unsafe-short-body)
    (values (list :kind kind :flags (aref buffer (+ pos 9))
                  :stamp (unpack-le buffer (+ pos 16) 8)
                  :key (coerce (subseq buffer ks ke) 'list)
                  :value (coerce (subseq buffer ke next) 'list)
                  :csn (when (= kind 4) (unpack-le buffer ke 8))) next)))
(defun unsafe-batch (buffer pos end)
  (let ((count 0) (start pos))
    (loop repeat 5
          do (multiple-value-bind (record next) (unsafe-record buffer pos end)
               (when (= (getf record :kind) 3)
                 (return-from unsafe-batch
                   (values next (getf record :stamp)
                           (unpack-le buffer (+ pos 40) 8) count)))
               (incf count)
               (setf pos next)))
    (error 'oracle-violation :reason :unsafe-missing-seal :context start)))
(defun resolved-history (records)
  (let ((outcomes (loop for r in records when (= (getf r :kind) 4)
                       collect (cons (getf r :stamp) (getf r :csn))))
        (history nil))
    (dolist (r records)
      (when (member (getf r :kind) '(1 2))
        (let ((csn (if (logbitp 0 (getf r :flags))
                       (cdr (assoc (getf r :stamp) outcomes)) (getf r :stamp))))
          (when csn
            (push (list csn (if (= (getf r :kind) 1) :put :delete)
                        (getf r :key) (getf r :value)) history)))))
    (stable-sort (nreverse history) #'< :key #'first)))
(defun result (status classification pos count records &optional reason offset)
  (checkpoint :risultato)
  (list :status status :classification classification :valid-length pos :valid-batches count
        :history (unless (eq status :faulted) (resolved-history records))
        :reason reason :offset offset))

;;; REQ: REQ-AFF-009 REQ-AFF-017
(defun recover (buffer fixture frontier &optional mutant)
  "F è una prova esplicita; nessuna scansione di garbage, nessuna scrittura."
  (let ((pos 0) (count 0) (records nil) (end (length buffer))
        (version (getf fixture :version)))
    (when (eq mutant :before-seal)
      (loop repeat 4 while (< pos end)
            do (checkpoint :record-prima-del-seal)
               (multiple-value-bind (r next) (verified-record buffer pos end version)
                 (setf records (append records (list r)) pos next)))
      (return-from recover (result :ok :tail pos 0 records :eager-publication pos)))
    (loop repeat 3 while (< pos end)
          do (checkpoint :lotto)
             (multiple-value-bind (next stamp durable record-count failure)
                 (handler-case
                     (if (eq mutant :ignore-crc)
                         (unsafe-batch buffer pos end)
                         (arcdocdb.record:verifica-lotto
                          buffer pos end (getf fixture :file-id) :version version
                          :log-kind :segment :file-offset 64 :max-records 4 :max-bytes 512))
                   (arcdocdb.conditions:corruption-detected (c)
                     (values nil nil nil nil c)))
               (when failure
                 (return-from recover
                   (result (if (and (< pos frontier) (not (eq mutant :all-tail))) :faulted :ok)
                           (if (and (< pos frontier) (not (eq mutant :all-tail))) :confirmed-damage :tail)
                           pos count records (arcdocdb.conditions:error-reason failure)
                           (arcdocdb.conditions:error-offset failure))))
               (require-fact (and (< pos next) (<= next end)) :verified-progress)
               (let ((expected (nth count (getf fixture :batches))))
                 (require-fact (and (= stamp (getf expected :stamp))
                                    (= durable (getf expected :durable))
                                    (= record-count (getf expected :count)))
                               :verified-batch-metadata (list stamp durable record-count)))
               (let ((cursor pos) (private nil))
                 (dotimes (i record-count)
                   (checkpoint :record)
                   (multiple-value-bind (r after)
                       (if (eq mutant :ignore-crc) (unsafe-record buffer cursor next)
                           (verified-record buffer cursor next version))
                     (push r private)
                     (setf cursor after)))
                 (checkpoint :pubblica-lotto-privato)
                 (setf records (append records (nreverse private))))
               (setf pos next)
               (incf count)))
    (if (and (< pos frontier) (not (eq mutant :all-tail)))
        (result :faulted :confirmed-damage pos count records :eof-before-frontier pos)
        (result :ok (if (= count 3) :complete :tail) pos count records))))

;;; REQ: REQ-AFF-007 REQ-AFF-017
(defun run-read (buffer immutable fixture frontier &key halt-at mutant)
  (incf (meter-recoveries *meter*))
  (enforce :recovery-limit (meter-recoveries *meter*) (getf *limits* :recovery-limit))
  (let ((*plan-step* 0) (*halt-at* halt-at))
    (unwind-protect
         (let ((answer (handler-case (recover buffer fixture frontier mutant)
                         (read-interrupted (c)
                           (list :status :interrupted :checkpoint (interruption-index c)
                                 :label (interruption-label c))))))
           (setf (meter-maximum-steps *meter*)
                 (max (meter-maximum-steps *meter*) *plan-step*))
           (values answer *plan-step*))
      (require-fact (equalp buffer immutable) :source-bytes-mutated))))

;;; REQ: REQ-VAL-001 REQ-AFF-009
;;; Oracle descritto dal guasto enumerato, non dai CRC o dal decoder sotto prova.
(defun intact-prefix (fixture fault)
  (case (first fault)
    (:clean 3)
    (:cut (loop for batch in (getf fixture :batches)
                count (<= (getf batch :end) (second fault))))
    (:flip (or (position-if (lambda (batch) (< (second fault) (getf batch :end)))
                            (getf fixture :batches))
               (error 'oracle-violation :reason :fault-outside-fixture :context fault)))
    (otherwise (error 'oracle-violation :reason :unknown-fault :context fault))))
(defun expected-result (fixture prefix confirmed)
  (let ((damaged (< prefix confirmed)))
    (list :status (if damaged :faulted :ok)
          :classification (if damaged :confirmed-damage (if (= prefix 3) :complete :tail))
          :valid-length (prefix-end fixture prefix) :valid-batches prefix
          :history (unless damaged (nth prefix (getf fixture :histories))))))
(defun matches-oracle (actual expected)
  (every (lambda (key) (equal (getf actual key) (getf expected key)))
         '(:status :classification :valid-length :valid-batches :history)))
(defun test-scenario (buffer fixture fault fixture-index rows)
  (let ((immutable (copy-seq buffer)) (prefix (intact-prefix fixture fault)))
    (let ((confirmed (getf fixture :confirmed-lots)))
      (time-budget)
      (incf (meter-cases *meter*))
      (enforce :case-limit (meter-cases *meter*) (getf *limits* :case-limit))
      (let* ((*active-case* (list :fixture fixture-index :fault fault :confirmed-lots confirmed))
             (frontier (prefix-end fixture confirmed))
             (expected (expected-result fixture prefix confirmed)))
        (multiple-value-bind (actual steps) (run-read buffer immutable fixture frontier)
          (require-fact (matches-oracle actual expected) :committed-history
                        (list :expected expected :actual actual))
          (dotimes (stop steps)
            (let ((interrupted (run-read buffer immutable fixture frontier :halt-at stop)))
              (require-fact (and (eq (getf interrupted :status) :interrupted)
                                 (= (getf interrupted :checkpoint) stop))
                            :missing-interruption interrupted)
              (incf (meter-interruptions *meter*)))
            (let ((restarted (run-read buffer immutable fixture frontier)))
              (require-fact (equal restarted actual) :read-idempotence (list actual restarted))
              (incf (meter-restarts *meter*))))
          (push (list :fixture fixture-index :fault fault :confirmed-lots confirmed
                      :expected-valid-lots prefix :actual-valid-lots (getf actual :valid-batches)
                      :status (getf actual :status) :classification (getf actual :classification)
                      :reason (getf actual :reason) :offset (getf actual :offset)
                      :checkpoints steps :interruptions steps :restarts steps
                      :history-matched t :source-unchanged t) rows))))
    rows))

;;; REQ: REQ-AFF-002 REQ-AFF-009 REQ-VAL-001
(defun witness (fixture fault bytes frontier mutant pertinent)
  (let* ((immutable (copy-seq bytes)) (*active-case* (list :mutant mutant :fault fault))
         (prefix (intact-prefix fixture fault))
         (confirmed (position frontier (loop for n below 4 collect (prefix-end fixture n)))))
    (require-fact confirmed :witness-frontier)
    (let* ((expected (expected-result fixture prefix confirmed))
           (correct (run-read bytes immutable fixture frontier))
           (broken (run-read bytes immutable fixture frontier :mutant mutant)))
      (require-fact (matches-oracle correct expected) :witness-correct expected)
      (require-fact (and (not (matches-oracle broken expected))
                         (funcall pertinent expected broken)) :witness-not-pertinent broken)
      (list :mutant mutant :fault fault :frontier frontier :input-bytes bytes
            :expected expected :correct correct :actual broken :pertinent-violation t
            :source-unchanged t))))
(defun negative-controls (fixtures)
  (let* ((fixture (nth 2 fixtures)) (original (getf fixture :bytes)) (damaged (copy-seq original))
         (crc-fixture (nth 1 fixtures)) (crc-damaged (copy-seq (getf crc-fixture :bytes))))
    ;; Primo valore CBOR: 1 diventa 0, cornice e CRC restano quelli originali.
    (setf (aref damaged 25) (logxor 1 (aref damaged 25)))
    (setf (aref crc-damaged 25) (logxor 1 (aref crc-damaged 25)))
    (list
     (witness crc-fixture '(:flip 25 0) crc-damaged (prefix-end crc-fixture 1) :ignore-crc
              (lambda (expected broken)
                (and (eq (getf expected :status) :faulted) (eq (getf broken :status) :ok)
                     (equal (fourth (first (getf broken :history))) '(0)))))
     (witness (first fixtures) (list :cut 52) (subseq original 0 52) 0 :before-seal
              (lambda (expected broken)
                (and (null (getf expected :history))
                     (equal (getf broken :history) '((10 :put (97) (1)) (10 :put (98) (2)))))))
     (witness fixture '(:flip 25 0) damaged (prefix-end fixture 2) :all-tail
              (lambda (expected broken)
                (and (eq (getf expected :status) :faulted) (eq (getf broken :status) :ok)
                     (eq (getf broken :classification) :tail) (null (getf broken :history))))))))

;;; REQ: REQ-FOR-003 REQ-AFF-009
(defun semantic-controls (fixture)
  (let* ((original (getf fixture :bytes)) (batch (first (getf fixture :batches)))
         (seal (getf batch :seal-start)) (body (+ seal 24)) (end (getf batch :end))
         (reports nil))
    (dolist (field '(0 8 16 24 28))
      (let ((buffer (copy-seq original)))
        (setf (aref buffer (+ body field)) (logxor 1 (aref buffer (+ body field))))
        (pack-le buffer (+ seal 4) 4 (bitwise-crc buffer body end))
        (pack-le buffer seal 4 (bitwise-crc buffer (+ seal 4) body))
        (let* ((immutable (copy-seq buffer))
               (*active-case* (list :seal-semantic-field field))
               (actual (run-read buffer immutable fixture (prefix-end fixture 2))))
          (require-fact (and (eq (getf actual :status) :faulted)
                             (eq (getf actual :reason) :seal-mismatch))
                        :seal-semantic-not-rejected actual)
          (push (list :seal-body-offset field :input-bytes buffer :actual actual
                      :source-unchanged t :crc-repaired-independently t) reports))))
    (nreverse reports)))

;;; REQ: REQ-AFF-009
(defun unwitnessed-last-flush (fixtures)
  (let* ((before (nth 2 fixtures)) (after (nth 3 fixtures))
         (original (getf after :bytes)) (buffer (copy-seq original))
         (pos (+ 25 (getf (third (getf after :batches)) :start)))
         (*active-case* (list :unwitnessed-last-flush :byte pos)))
    (require-fact (equalp original (getf before :bytes)) :last-flush-must-have-identical-bytes)
    (setf (aref buffer pos) (logxor 1 (aref buffer pos)))
    (let* ((immutable (copy-seq buffer))
           (tail (run-read buffer immutable before (getf before :frontier)))
           (faulted (run-read buffer immutable after (getf after :frontier))))
      (require-fact (and (matches-oracle tail (expected-result before 2 2))
                         (matches-oracle faulted (expected-result after 2 3)))
                    :last-flush-witness (list tail faulted))
      (list :input-bytes buffer :fault (list :flip pos 0)
            :bytes-identical-before-damage t :frontier-before (getf before :frontier)
            :frontier-after (getf after :frontier) :tail tail :faulted faulted
            :on-disk-distinction :absent :source-unchanged t))))

;;; REQ: REQ-VAL-001 REQ-AFF-007 REQ-AFF-008
(defun check (&key (case-limit 60000) (step-limit 16) (recovery-limit 2000000)
                   (read-limit 40000000) (seconds-limit 150))
  "Campagna finita esaustiva. Ogni limite esaurito segnala BUDGET-EXHAUSTED."
  (let* ((*limits* (list :case-limit case-limit :step-limit step-limit
                        :recovery-limit recovery-limit :read-limit read-limit
                        :seconds-limit seconds-limit :buffer-limit 512 :batch-limit 3
                        :records-per-batch 4 :verifier-byte-limit 512))
         (*meter* (make-meter)) (*started* (get-internal-real-time))
         (*active-case* nil) (rows nil) (fixture-reports nil)
         (fixtures (loop for version in '(1 2) append
                         (loop for transactional in '(nil t) append
                               (loop for confirmed below 4 collect
                                     (make-fixture version transactional confirmed))))))
    (loop for (key value) on *limits* by #'cddr
          do (require-fact (and (realp value) (plusp value)) :invalid-budget (list key value)))
    (require-fact (= (bitwise-crc (octets 49 50 51 52 53 54 55 56 57)) #xe3069283)
                  :crc-known-vector)
    (require-fact (zerop (bitwise-crc (octets))) :crc-empty)
    (loop for fixture in fixtures for index from 0
          do (let* ((original (getf fixture :bytes)) (immutable (copy-seq original))
                    (size (length original)) (initial-cases (meter-cases *meter*)))
               (require-fact (= (getf fixture :frontier)
                                (prefix-end fixture (getf fixture :confirmed-lots)))
                             :explicit-frontier-mismatch)
               (require-fact (every (lambda (batch) (<= (getf batch :durable)
                                                        (+ 64 (getf fixture :frontier))))
                                    (getf fixture :batches))
                             :seal-frontier-exceeds-model-fact)
               (setf rows (test-scenario original fixture '(:clean) index rows))
               (dotimes (cut size)
                 (setf rows (test-scenario (subseq original 0 cut) fixture (list :cut cut) index rows)))
               (dotimes (pos size)
                 (dotimes (bit 8)
                   (let ((buffer (copy-seq original)))
                     (setf (aref buffer pos) (logxor (ash 1 bit) (aref buffer pos)))
                     (setf rows (test-scenario buffer fixture (list :flip pos bit) index rows)))))
               (require-fact (equalp original immutable) :fixture-mutated)
               (push (list :fixture index :name (getf fixture :name) :byte-length size
                           :identity-scenarios 1 :truncation-scenarios size :monobit-scenarios (* 8 size)
                           :frontiers 1 :confirmed-lots (getf fixture :confirmed-lots)
                           :frontier (getf fixture :frontier)
                           :cases (- (meter-cases *meter*) initial-cases)) fixture-reports)))
    (let* ((negatives (negative-controls fixtures))
           (semantics (semantic-controls (nth 2 fixtures)))
           (last-flush (unwitnessed-last-flush fixtures))
           (ordered-rows (nreverse rows))
           (expected-cases (loop for fixture in fixtures sum
                                (1+ (* 9 (length (getf fixture :bytes)))))))
      (time-budget)
      (require-fact (= (meter-cases *meter*) expected-cases (length ordered-rows)) :case-count)
      (require-fact (= (meter-interruptions *meter*) (meter-restarts *meter*)) :restart-count)
      (list :status :ok :schema-version 1 :module :byte-crash :phase 0
            :limits *limits* :fixtures fixtures :fixture-reports (nreverse fixture-reports)
            :cases (meter-cases *meter*) :case-reports ordered-rows
            :classification-counts
            (loop for class in '(:complete :tail :confirmed-damage)
                  collect (list class (count class ordered-rows :key (lambda (r) (getf r :classification)))))
            :recoveries (meter-recoveries *meter*) :checkpoints (meter-checkpoints *meter*)
            :maximum-checkpoints-per-recovery (meter-maximum-steps *meter*)
            :interruptions (meter-interruptions *meter*) :restarts (meter-restarts *meter*)
            :negative-controls negatives :semantic-controls semantics
            :unwitnessed-last-flush last-flush
            :limitations '(:explicit-frontier :unwitnessed-last-flush :finite-byte-domain
                           :single-fault :no-real-filesystem :no-crc-collision-free-claim
                           :no-active-decision-table :no-manifest-writes :no-benchmark)))))
