(require :asdf)
(require :sb-posix)
(declaim (optimize (safety 3) (debug 3)))
(unless (or (null (uiop:command-line-arguments))
            (equal (uiop:command-line-arguments) '("--check"))
            (equal (uiop:command-line-arguments) '("--bench")))
  (error "Uso: run.lisp [--check|--bench]"))
(let* ((base (uiop:pathname-directory-pathname *load-truename*))
       (output (merge-pathnames (format nil "out/suite-~D-~D/" (get-universal-time)
                                        (sb-posix:getpid)) base)))
  (ensure-directories-exist output)
  (handler-bind ((warning (lambda (c) (error "Avviso non ammesso: ~A" c))))
    (dolist (name '("core" "pubblicazione" "scadenza" "compaction" "memoria" "suite"))
      (multiple-value-bind (fasl warnings failure)
          (compile-file (merge-pathnames (format nil "~A.lisp" name) base)
                        :output-file (merge-pathnames (format nil "~A.fasl" name) output)
                        :verbose nil :print nil)
        (when (or warnings failure (null fasl)) (error "Compilazione non valida: ~A" name))
        (load fasl :verbose nil :print nil)))))
(write (uiop:symbol-call :arcdocdb.spk07.suite :check) :pretty t)
(terpri)
