(require :asdf)
(unless (or (null (uiop:command-line-arguments))
            (equal (uiop:command-line-arguments) '("--check"))
            (equal (uiop:command-line-arguments) '("--bench")))
  (error "Uso: run.lisp [--check|--bench]"))
(let* ((base (uiop:pathname-directory-pathname *load-truename*))
       (source (merge-pathnames "core.lisp" base))
       (output (merge-pathnames "out/core.fasl" base)))
  (ensure-directories-exist output)
  (handler-bind ((warning (lambda (c) (error "Avviso non ammesso: ~A" c))))
    (load (compile-file source :output-file output))))
(write (uiop:symbol-call :arcdocdb.spk07 :check) :pretty t)
(terpri)
