(require :asdf)
(require :sb-posix)
(declaim (optimize (safety 3) (debug 3)))
(unless (or (null (uiop:command-line-arguments))
            (equal (uiop:command-line-arguments) '("--check"))
            (equal (uiop:command-line-arguments) '("--bench")))
  (error "Uso: run.lisp [--check|--bench]"))
(let* ((base (uiop:pathname-directory-pathname *load-truename*))
       (output (merge-pathnames (format nil "out/suite-~D-~D/" (get-universal-time)
                                        (sb-posix:getpid)) base)))
  (ensure-directories-exist output)
  (handler-bind ((warning (lambda (c) (error "Avviso non ammesso: ~A" c))))
    (multiple-value-bind (fasl warnings failure)
        (compile-file (merge-pathnames "../../src/package.lisp" base)
                      :output-file (merge-pathnames "root-package.fasl" output)
                      :verbose nil :print nil)
      (when (or warnings failure (null fasl)) (error "Package radice non compilato"))
      (load fasl :verbose nil :print nil))
    (dolist (name '("package" "conditions" "binary" "crc32c" "record" "batch"))
      (multiple-value-bind (fasl warnings failure)
          (compile-file (merge-pathnames (format nil "../../src/foundation/~A.lisp" name) base)
                        :output-file (merge-pathnames (format nil "foundation-~A.fasl" name) output)
                        :verbose nil :print nil)
        (when (or warnings failure (null fasl)) (error "Fondazioni non compilate: ~A" name))
        (load fasl :verbose nil :print nil)))
    (dolist (name '("core" "pubblicazione" "scadenza" "compaction" "memoria"
                   "seqlock-readers" "byte-crash" "suite"))
      (multiple-value-bind (fasl warnings failure)
          (compile-file (merge-pathnames (format nil "~A.lisp" name) base)
                        :output-file (merge-pathnames (format nil "~A.fasl" name) output)
                        :verbose nil :print nil)
        (when (or warnings failure (null fasl)) (error "Compilazione non valida: ~A" name))
        (load fasl :verbose nil :print nil)))))
(write (uiop:symbol-call :arcdocdb.spk07.suite :check) :pretty t)
(terpri)
