;;;; SPK-10, esperimento C4: frammento primario v2, non motore di produzione.
(defpackage #:arcdocdb.spk10.indice
  (:use #:cl)
  (:export #:check #:benchmark #:make-indice #:inserisci #:elimina #:leggi
           #:statistiche #:limite-indice #:limite-motivo))
(in-package #:arcdocdb.spk10.indice)
(declaim (optimize (safety 3) (speed 2) (debug 1)))

(deftype u32 () '(unsigned-byte 32))
(deftype u64 () '(unsigned-byte 64))
(deftype ottetti () '(simple-array (unsigned-byte 8) (*)))
(deftype parole () '(simple-array (unsigned-byte 64) (*)))
(defconstant +mask64+ #xffffffffffffffff)
(defconstant +seed+ #xcbf29ce484222325)
(defconstant +prime+ #x100000001b3)
(defconstant +documento-max+ 16777216)
(defconstant +chiave-max+ 65535)
(defconstant +header+ 24)
(defconstant +record-max+ 16842775)
(defconstant +parole-slot+ 5)
(defconstant +byte-slot+ 41)
(defconstant +vuoto+ 255)
(defconstant +eliminato+ 254)
(defconstant +gruppo+ 8)
(defconstant +blocco+ 4096)
(defconstant +soglia-seq+ #x4000000000000000)
(defconstant +memoria-bench-max+ 134217728)

(define-condition limite-indice (error)
  ((motivo :initarg :motivo :reader limite-motivo))
  (:report (lambda (c s) (format s "Limite SPK-10 indice: ~S" (limite-motivo c)))))

;;; OWNER: un writer per indice; reader leggono soltanto array e root.
;;; SHARED: nessuno stato tra Serie. Seriali preparazione e pubblicazione writer.
;;; REQ: REQ-LIM-001 REQ-LIM-003 REQ-IDX-003 REQ-IDX-005 REQ-IDX-007
(defstruct (frammento (:constructor %frammento))
  (capacita 8 :type fixnum :read-only t)
  (ctrl (make-array 0 :element-type '(unsigned-byte 8)) :type ottetti :read-only t)
  (slots (make-array 0 :element-type '(unsigned-byte 64)) :type parole :read-only t)
  (arena (make-array 0 :element-type '(unsigned-byte 8)) :type ottetti)
  (usati 0 :type fixnum)
  (vivi 0 :type fixnum)
  (morti 0 :type fixnum)
  (byte-vivi 0 :type fixnum))
(defstruct (radice (:constructor %radice (generazione frammento)))
  (generazione 0 :type u64 :read-only t)
  (frammento (%frammento) :type frammento :read-only t))
(defstruct (indice (:constructor %indice))
  (root (%radice 0 (%frammento)) :type radice)
  (max-chiave +chiave-max+ :type fixnum :read-only t)
  (max-documento +documento-max+ :type fixnum :read-only t)
  (max-arena 8388608 :type fixnum :read-only t)
  (budget-copia 16777216 :type fixnum :read-only t)
  (budget-transitorio +memoria-bench-max+ :type fixnum :read-only t)
  (budget-ticks 500000 :type integer :read-only t)
  (clock #'get-internal-real-time :type function :read-only t)
  (inserimenti 0 :type integer) (aggiornamenti 0 :type integer)
  (eliminazioni 0 :type integer) (rebuild 0 :type integer)
  (crescite 0 :type integer) (byte-copiati 0 :type integer)
  (max-byte-copiati 0 :type fixnum) (max-slot-visitati 0 :type fixnum)
  (max-slot-copiati 0 :type fixnum) (max-riferimenti 0 :type fixnum)
  (picco-payload 0 :type fixnum) (picco-transitorio 0 :type fixnum)
  (max-preparazione-ticks 0 :type integer))

(declaim (ftype (function (t integer integer) integer) intero-limitato))
(defun intero-limitato (x minimo massimo)
  "Controlla un intervallo senza coercizioni o troncamenti."
  (unless (typep x `(integer ,minimo ,massimo))
    (error 'type-error :datum x :expected-type `(integer ,minimo ,massimo)))
  x)
(declaim (ftype (function (keyword) nil) rifiuta))
(defun rifiuta (motivo)
  "Segnala un limite previsto; i chiamanti lo usano prima di pubblicare."
  (error 'limite-indice :motivo motivo))
(declaim (ftype (function (frammento) fixnum) payload))
(defun payload (f)
  "Payload degli array e un riferimento di directory; esclude header e RSS."
  (+ (* +byte-slot+ (frammento-capacita f)) (length (frammento-arena f)) 8))
(declaim (ftype (function (fixnum fixnum) frammento) nuovo-frammento))
(defun nuovo-frammento (capacita arena-byte)
  "Alloca array specializzati; il frammento è inizialmente fuori dalla root."
  (%frammento :capacita capacita
              :ctrl (make-array capacita :element-type '(unsigned-byte 8)
                                        :initial-element +vuoto+)
              :slots (make-array (* capacita +parole-slot+)
                                 :element-type '(unsigned-byte 64) :initial-element 0)
              :arena (make-array arena-byte :element-type '(unsigned-byte 8)
                                           :initial-element 0)))

(declaim (ftype (function (&key (:capacity integer) (:max-key-bytes integer)
                               (:max-document-bytes integer) (:max-arena-bytes integer)
                               (:copy-byte-budget integer) (:transient-byte-budget integer)
                               (:maintenance-seconds real) (:clock function)) indice)
                make-indice))
(defun make-indice (&key (capacity 16384) (max-key-bytes +chiave-max+)
                        (max-document-bytes +documento-max+) (max-arena-bytes 8388608)
                        (copy-byte-budget 16777216)
                        (transient-byte-budget +memoria-bench-max+)
                        (maintenance-seconds 1/2) (clock #'get-internal-real-time))
  "Un frammento, arena vuota. Budget di copie e memoria in byte; tempo cooperativo."
  (intero-limitato capacity 8 32768)
  (unless (= 1 (logcount capacity)) (rifiuta :capacita-non-potenza-di-due))
  (intero-limitato max-key-bytes 1 +chiave-max+)
  (intero-limitato max-document-bytes 1 +documento-max+)
  (intero-limitato max-arena-bytes 0 #xffffffff)
  (intero-limitato copy-byte-budget 0 most-positive-fixnum)
  (intero-limitato transient-byte-budget 0 most-positive-fixnum)
  (unless (typep maintenance-seconds '(real 0 3))
    (error 'type-error :datum maintenance-seconds :expected-type '(real 0 3)))
  (check-type clock function)
  (let ((byte (+ (* +byte-slot+ capacity) 8)))
    (when (> byte transient-byte-budget) (rifiuta :memoria-iniziale))
    (%indice :root (%radice 0 (nuovo-frammento capacity 0))
             :max-chiave max-key-bytes :max-documento max-document-bytes
             :max-arena max-arena-bytes :budget-copia copy-byte-budget
             :budget-transitorio transient-byte-budget :clock clock
             :budget-ticks (floor (* maintenance-seconds internal-time-units-per-second))
             :picco-payload byte :picco-transitorio byte)))

;;; REQ: REQ-LIM-003. Hash streaming senza subseq o vettori temporanei.
(declaim (inline hash-intervallo hash-chiave impronta posizione stessa-chiave-p metadata))
(declaim (ftype (function (ottetti fixnum fixnum) u64) hash-intervallo))
(defun hash-intervallo (arena off len)
  "FNV-1a u64 con seed fisso; attraversa esattamente LEN byte. Non crittografico."
  (declare (type ottetti arena) (type fixnum off len))
  (let ((h +seed+))
    (declare (type u64 h))
    (dotimes (n len h)
      (declare (type fixnum n))
      (setf h (logand +mask64+ (* +prime+ (logxor h (aref arena (+ off n)))))))))
(declaim (ftype (function (ottetti) u64) hash-chiave))
(defun hash-chiave (chiave)
  "Kernel tipizzato; la lunghezza non è limitata a sedici byte."
  (declare (type ottetti chiave))
  (hash-intervallo chiave 0 (length chiave)))
(declaim (ftype (function (u64) (unsigned-byte 7)) impronta))
(defun impronta (h)
  "Sette bit nel controllo; l'impronta non decide l'uguaglianza."
  (declare (type u64 h))
  (ldb (byte 7 0) h))
(declaim (ftype (function (u64 fixnum fixnum) fixnum) posizione))
(defun posizione (h capacita n)
  "Gruppi contigui da otto con wrap; al massimo CAPACITA slot."
  (declare (type u64 h) (type fixnum capacita n))
  (logand (1- capacita) (+ (logand (1- capacita) (ash h -7)) n)))
(declaim (ftype (function (ottetti ottetti fixnum fixnum) boolean) stessa-chiave-p))
(defun stessa-chiave-p (chiave arena off len)
  "Confronto binario completo, inclusi zero e byte sopra 127."
  (declare (type ottetti chiave arena) (type fixnum off len))
  (and (= (length chiave) len)
       (<= (+ off len) (length arena))
       (dotimes (n len t)
         (unless (= (aref chiave n) (aref arena (+ off n))) (return nil)))))
(declaim (ftype (function (u32 (unsigned-byte 16) (unsigned-byte 8)) u64) metadata))
(defun metadata (off len flag)
  "Parola 2: off32, len16, flag8, riservato8 zero."
  (declare (type u32 off) (type (unsigned-byte 16) len) (type (unsigned-byte 8) flag))
  (logior off (ash len 32) (ash flag 48)))
(declaim (ftype (function (indice ottetti) null) valida-chiave))
(defun valida-chiave (i chiave)
  "Rifiuta prima di hashing o allocazione; accetta solo ottetti specializzati."
  (check-type chiave ottetti)
  (unless (<= 1 (length chiave) (indice-max-chiave i)) (rifiuta :lunghezza-chiave))
  nil)
(declaim (ftype (function (indice ottetti t t t t) null) valida-entry))
(defun valida-entry (i chiave csn segmento off len)
  "CSN u64, segmento/offset/lunghezza u32, limite documentale sul totale record."
  (valida-chiave i chiave)
  (check-type csn u64)
  (check-type segmento u32)
  (check-type off u32)
  (check-type len u32)
  (let ((minimo (+ +header+ (length chiave))))
    (unless (<= minimo len (+ minimo (indice-max-documento i)))
      (rifiuta :lunghezza-record)))
  nil)

(declaim (ftype (function (frammento ottetti u64) (values fixnum boolean)) cerca-writer))
(defun cerca-writer (f chiave h)
  "Un writer; tombstone riusabile e confronto di tutta la chiave."
  (let ((libero -1) (c (frammento-capacita f)) (ctrl (frammento-ctrl f)))
    (dotimes (g (/ c +gruppo+) (values libero nil))
      (dotimes (n +gruppo+)
        (let* ((s (posizione h c (+ (* g +gruppo+) n))) (b (* s +parole-slot+))
               (control (aref ctrl s)) (meta (aref (frammento-slots f) (+ b 2))))
          (when (= control +vuoto+)
            (return-from cerca-writer (values (if (minusp libero) s libero) nil)))
          (when (and (= control +eliminato+) (minusp libero)) (setf libero s))
          (when (and (= control (impronta h))
                     (stessa-chiave-p chiave (frammento-arena f)
                                     (ldb (byte 32 0) meta) (ldb (byte 16 32) meta)))
            (return-from cerca-writer (values s t))))))))
(declaim (ftype (function (frammento u64) fixnum) slot-vuoto))
(defun slot-vuoto (f h)
  "Solo costruzione di un frammento nuovo; visita al massimo C slot."
  (dotimes (n (frammento-capacita f))
    (let ((s (posizione h (frammento-capacita f) n)))
      (when (= +vuoto+ (aref (frammento-ctrl f) s)) (return-from slot-vuoto s))))
  (rifiuta :invariante-copia-satura))
(declaim (ftype (function (frammento fixnum u64 u64 u64 u32 u64) null) scrivi-campi))
(defun scrivi-campi (f s csn loc meta len h)
  "Pubblica campi sotto seqlock, poi controllo. Nessuna validazione tardiva."
  (let* ((slots (frammento-slots f)) (b (* s +parole-slot+))
         (seq (aref slots (+ b 3))))
    (assert (evenp seq))
    (assert (< seq (- +soglia-seq+ 2)))
    (setf (aref slots (+ b 3)) (1+ seq))
    (sb-thread:barrier (:write))
    (setf (aref slots b) csn (aref slots (+ b 1)) loc
          (aref slots (+ b 2)) meta (aref slots (+ b 4)) len)
    (sb-thread:barrier (:write))
    (setf (aref slots (+ b 3)) (+ seq 2))
    (sb-thread:barrier (:write))
    (setf (aref (frammento-ctrl f) s) (impronta h)))
  nil)
(declaim (ftype (function (indice) integer) ora))
(defun ora (i)
  "Clock di wall time in tick, iniettabile; valori non negativi."
  (let ((ticks (funcall (indice-clock i))))
    (check-type ticks (integer 0))
    ticks))
(declaim (ftype (function (indice integer) null) controlla-tempo))
(defun controlla-tempo (i scadenza)
  "Cooperativo; nessuna promessa sulla durata di allocazione, GC o scheduling."
  (when (>= (ora i) scadenza) (rifiuta :tempo-preparazione))
  nil)
(declaim (ftype (function (indice ottetti fixnum ottetti fixnum fixnum integer) null)
                copia-limitata))
(defun copia-limitata (i fonte off-fonte dest off-dest len scadenza)
  "Copia per blocchi di al massimo 4096 byte in un array ancora privato."
  (dotimes (blocco (ceiling len +blocco+))
    (controlla-tempo i scadenza)
    (let* ((off (* blocco +blocco+)) (fine (min len (+ off +blocco+))))
      (replace dest fonte :start1 (+ off-dest off) :end1 (+ off-dest fine)
                         :start2 (+ off-fonte off) :end2 (+ off-fonte fine))))
  nil)
(declaim (ftype (function (fixnum fixnum fixnum) fixnum) capacita-arena))
(defun capacita-arena (corrente richiesto massimo)
  "Raddoppio fino al tetto; al massimo 33 passi per il dominio u32."
  (when (> richiesto massimo) (rifiuta :arena))
  (let ((n corrente))
    (dotimes (passo 33)
      (when (>= n richiesto) (return-from capacita-arena n))
      (setf n (min massimo (max 32 (* 2 n)))))
    (rifiuta :invariante-crescita)))
(declaim (ftype (function (indice fixnum fixnum) null) preflight-byte))
(defun preflight-byte (i copie transitorio)
  "Nessun contatore o array mutato nei rifiuti di budget."
  (when (> copie (indice-budget-copia i)) (rifiuta :byte-copiati))
  (when (> transitorio (indice-budget-transitorio i)) (rifiuta :memoria-transitoria))
  nil)
(declaim (ftype (function (indice frammento frammento fixnum integer) fixnum) copia-vivi))
(defun copia-vivi (i fonte dest escluso scadenza)
  "Rebuild: C slot visitati, chiavi vive soltanto; hashing senza staging per entry."
  (let ((copiati 0) (slots (frammento-slots fonte)) (arena (frammento-arena fonte)))
    (dotimes (s (frammento-capacita fonte) copiati)
      (controlla-tempo i scadenza)
      (when (and (/= s escluso) (< (aref (frammento-ctrl fonte) s) 128))
        (let* ((b (* s +parole-slot+)) (meta (aref slots (+ b 2)))
               (off (ldb (byte 32 0) meta)) (len (ldb (byte 16 32) meta))
               (h (hash-intervallo arena off len)) (slot (slot-vuoto dest h))
               (nuovo-off (frammento-usati dest)))
          (copia-limitata i arena off (frammento-arena dest) nuovo-off len scadenza)
          (scrivi-campi dest slot (aref slots b) (aref slots (+ b 1))
                        (metadata nuovo-off len 1) (ldb (byte 32 0) (aref slots (+ b 4))) h)
          (incf (frammento-usati dest) len) (incf (frammento-byte-vivi dest) len)
          (incf (frammento-vivi dest)) (incf copiati))))))
(declaim (ftype (function (indice radice radice) null) pubblica-root))
(defun pubblica-root (i vecchia nuova)
  "CAS unico: confine di visibilità RAM, nessun commit durevole."
  (sb-thread:barrier (:write))
  (unless (eq vecchia (sb-ext:compare-and-swap (indice-root i) vecchia nuova))
    (rifiuta :violazione-writer-unico))
  nil)
(declaim (ftype (function (indice fixnum fixnum fixnum fixnum integer boolean boolean) null)
                registra-costi))
(defun registra-costi (i copie transitorio visitati copiati ticks rebuild crescita)
  "Solo dopo il successo; i reader non scrivono contatori comuni."
  (incf (indice-byte-copiati i) copie)
  (setf (indice-max-byte-copiati i) (max copie (indice-max-byte-copiati i))
        (indice-picco-transitorio i) (max transitorio (indice-picco-transitorio i))
        (indice-picco-payload i) (max (payload (radice-frammento (indice-root i)))
                                     (indice-picco-payload i))
        (indice-max-slot-visitati i) (max visitati (indice-max-slot-visitati i))
        (indice-max-slot-copiati i) (max copiati (indice-max-slot-copiati i))
        (indice-max-preparazione-ticks i) (max ticks (indice-max-preparazione-ticks i)))
  (when rebuild (incf (indice-rebuild i)) (setf (indice-max-riferimenti i) 1))
  (when crescita (incf (indice-crescite i)))
  nil)

(declaim (ftype (function (indice radice ottetti fixnum boolean) boolean) richiede-rebuild-p))
(defun richiede-rebuild-p (i root chiave s presente)
  "Pulizia tombstone/byte morti o ricambio seqlock; nessuna divisione implicita."
  (let ((f (radice-frammento root)))
    (or (and (>= s 0) (>= (aref (frammento-slots f) (+ (* s +parole-slot+) 3))
                              (- +soglia-seq+ 2)))
        (and (not presente)
             (or (>= (frammento-morti f) (/ (frammento-capacita f) 4))
                 (> (+ (frammento-usati f) (length chiave)) (indice-max-arena i))
                 (> (- (frammento-usati f) (frammento-byte-vivi f))
                    (max 1024 (frammento-byte-vivi f))))))))
(declaim (ftype (function (frammento fixnum ottetti u64 u64 u32 u64 boolean) null)
                termina-inserimento))
(defun termina-inserimento (f s copia csn loc len h presente)
  "Fase finale bounded: copia <=65535 byte, slot e contatori; preflight già completo."
  (let* ((control (aref (frammento-ctrl f) s)) (b (* s +parole-slot+))
         (off (if presente (ldb (byte 32 0) (aref (frammento-slots f) (+ b 2)))
                  (frammento-usati f)))
         (key-len (if presente (ldb (byte 16 32) (aref (frammento-slots f) (+ b 2)))
                      (length copia))))
    (unless presente
      (replace (frammento-arena f) copia :start1 off :end1 (+ off key-len))
      (incf (frammento-usati f) key-len) (incf (frammento-byte-vivi f) key-len)
      (incf (frammento-vivi f))
      (when (= control +eliminato+) (decf (frammento-morti f))))
    (scrivi-campi f s csn loc (metadata off key-len 1) len h))
  nil)
(declaim (ftype (function (indice radice ottetti fixnum boolean u64 u64 u32 u64) null)
                inserisci-diretto))
(defun inserisci-diretto (i root chiave s presente csn loc len h)
  "Prepara staging e possibile arena nuova, poi pubblica senza ulteriori rifiuti."
  (let* ((f (radice-frammento root)) (inizio (ora i))
         (scadenza (+ inizio (indice-budget-ticks i)))
         (key-len (if presente 0 (length chiave)))
         (vecchia (frammento-arena f))
         (cap (capacita-arena (length vecchia) (+ (frammento-usati f) key-len)
                             (indice-max-arena i)))
         (crescita (> cap (length vecchia)))
         (copie (+ (* 2 key-len) (if crescita (frammento-usati f) 0)))
         (transitorio (+ (payload f) key-len (if crescita cap 0))))
    (preflight-byte i copie transitorio)
    (controlla-tempo i scadenza)
    (let ((copia (make-array key-len :element-type '(unsigned-byte 8)))
          (arena (if crescita (make-array cap :element-type '(unsigned-byte 8)
                                            :initial-element 0) vecchia)))
      (copia-limitata i chiave 0 copia 0 key-len scadenza)
      (when crescita
        (copia-limitata i vecchia 0 arena 0 (frammento-usati f) scadenza))
      (let ((fine (ora i)))
        (when (>= fine scadenza) (rifiuta :tempo-preparazione))
        (when crescita
          (setf (frammento-arena f) arena)
          (sb-thread:barrier (:write)))
        (termina-inserimento f s copia csn loc len h presente)
        (registra-costi i copie transitorio 0 0 (- fine inizio) nil crescita))))
  nil)
(declaim (ftype (function (indice radice ottetti fixnum boolean u64 u64 u32 u64) null)
                inserisci-rebuild))
(defun inserisci-rebuild (i root chiave s presente csn loc len h)
  "Integra il nuovo inserimento nel rebuild privato: nessuno swap parziale su rifiuto."
  (declare (type fixnum s))
  (assert (>= s 0))
  (let* ((fonte (radice-frammento root)) (inizio (ora i))
         (scadenza (+ inizio (indice-budget-ticks i)))
         (key-len (if presente 0 (length chiave)))
         (cap (capacita-arena 0 (+ (frammento-byte-vivi fonte) key-len) (indice-max-arena i)))
         (copie (+ (frammento-byte-vivi fonte) (* 2 key-len)))
         (transitorio (+ (payload fonte) (* +byte-slot+ (frammento-capacita fonte))
                         cap 8 key-len)))
    (when (= (radice-generazione root) +mask64+) (rifiuta :generazione-root))
    (preflight-byte i copie transitorio)
    (controlla-tempo i scadenza)
    (let* ((dest (nuovo-frammento (frammento-capacita fonte) cap))
           (nuova (%radice (1+ (radice-generazione root)) dest))
           (copia (make-array key-len :element-type '(unsigned-byte 8)))
           (copiati (copia-vivi i fonte dest -1 scadenza)))
      (copia-limitata i chiave 0 copia 0 key-len scadenza)
      (multiple-value-bind (slot trovato) (cerca-writer dest chiave h)
        (assert (eq trovato presente))
        (assert (>= slot 0))
        (termina-inserimento dest slot copia csn loc len h presente))
      (let ((fine (ora i)))
        (when (>= fine scadenza) (rifiuta :tempo-preparazione))
        (pubblica-root i root nuova)
        (registra-costi i copie transitorio (frammento-capacita fonte) copiati
                        (- fine inizio) t nil))))
  nil)

;;; REQ: REQ-LIM-001 REQ-LIM-003 REQ-IDX-003 REQ-IDX-005 REQ-IDX-007
(declaim (ftype (function (indice ottetti u64 u32 u32 u32) boolean) inserisci))
(defun inserisci (i chiave csn segmento offset lunghezza)
  "Writer unico. T nuova entry, NIL aggiornamento; condizioni prima della mutazione.
LUNGHEZZA include header24 e chiave; il documento ammesso occupa <=16MiB.
Il chiamante mantiene CHIAVE stabile durante la chiamata; l'indice ne possiede la copia."
  (check-type i indice)
  (valida-entry i chiave csn segmento offset lunghezza)
  (let* ((root (indice-root i)) (f (radice-frammento root)) (h (hash-chiave chiave))
         (loc (logior (ash segmento 32) offset)))
    (multiple-value-bind (s presente) (cerca-writer f chiave h)
      (when (and (not presente) (>= (frammento-vivi f) (* 7 (/ (frammento-capacita f) 8))))
        (rifiuta :capacita-frammento))
      (when (minusp s) (rifiuta :sondaggio-saturo))
      (if (richiede-rebuild-p i root chiave s presente)
          (inserisci-rebuild i root chiave s presente csn loc lunghezza h)
          (inserisci-diretto i root chiave s presente csn loc lunghezza h))
      (if presente (incf (indice-aggiornamenti i)) (incf (indice-inserimenti i)))
      (not presente))))

(declaim (ftype (function (indice radice fixnum) null) ricostruisci))
(defun ricostruisci (i root escluso)
  "Manutenzione privata; ESCLUSO=-1 copia tutti, altrimenti completa l'eliminazione."
  (let* ((fonte (radice-frammento root)) (inizio (ora i))
         (scadenza (+ inizio (indice-budget-ticks i)))
         (rimossi (if (minusp escluso) 0
                      (ldb (byte 16 32) (aref (frammento-slots fonte)
                                            (+ (* escluso +parole-slot+) 2)))))
         (copie (- (frammento-byte-vivi fonte) rimossi))
         (cap (capacita-arena 0 copie (indice-max-arena i)))
         (transitorio (+ (payload fonte) (* +byte-slot+ (frammento-capacita fonte)) cap 8)))
    (when (= (radice-generazione root) +mask64+) (rifiuta :generazione-root))
    (preflight-byte i copie transitorio)
    (controlla-tempo i scadenza)
    (let* ((dest (nuovo-frammento (frammento-capacita fonte) cap))
           (nuova (%radice (1+ (radice-generazione root)) dest))
           (copiati (copia-vivi i fonte dest escluso scadenza)) (fine (ora i)))
      (when (>= fine scadenza) (rifiuta :tempo-preparazione))
      (pubblica-root i root nuova)
      (registra-costi i copie transitorio (frammento-capacita fonte) copiati
                      (- fine inizio) t nil)))
  nil)
(declaim (ftype (function (frammento fixnum) null) elimina-slot))
(defun elimina-slot (f s)
  "Elimina sotto seqlock; il controllo diventa tombstone, mai vuoto."
  (let* ((slots (frammento-slots f)) (b (* s +parole-slot+))
         (seq (aref slots (+ b 3))) (meta (aref slots (+ b 2))))
    (assert (evenp seq))
    (assert (< seq (- +soglia-seq+ 2)))
    (setf (aref slots (+ b 3)) (1+ seq))
    (sb-thread:barrier (:write))
    (setf (aref slots (+ b 2)) (logand meta #x0000ffffffffffff))
    (sb-thread:barrier (:write))
    (setf (aref slots (+ b 3)) (+ seq 2))
    (sb-thread:barrier (:write))
    (setf (aref (frammento-ctrl f) s) +eliminato+)
    (decf (frammento-vivi f)) (incf (frammento-morti f))
    (decf (frammento-byte-vivi f) (ldb (byte 16 32) meta)))
  nil)
(declaim (ftype (function (indice ottetti) boolean) elimina))
(defun elimina (i chiave)
  "T se eliminata, NIL assente; nessuno storage o conferma durable."
  (check-type i indice)
  (valida-chiave i chiave)
  (let* ((root (indice-root i)) (f (radice-frammento root)))
    (multiple-value-bind (s presente) (cerca-writer f chiave (hash-chiave chiave))
      (unless presente (return-from elimina nil))
      (if (>= (aref (frammento-slots f) (+ (* s +parole-slot+) 3)) (- +soglia-seq+ 2))
          (ricostruisci i root s)
          (elimina-slot f s))
      (incf (indice-eliminazioni i))
      t)))

;;; REQ: REQ-IDX-003 REQ-IDX-007
(declaim (ftype (function (frammento fixnum ottetti u64 (or null function))
                         (values u64 u64 u32 keyword)) leggi-slot))
(defun leggi-slot (f s chiave h dopo-campi)
  "Seqlock: pari, barriera, campi/arena/confronto, barriera, stesso contatore."
  (let* ((slots (frammento-slots f)) (b (* s +parole-slot+))
         (seq (aref slots (+ b 3))))
    (when (oddp seq) (return-from leggi-slot (values 0 0 0 :retry)))
    (sb-thread:barrier (:read))
    (let* ((csn (aref slots b)) (loc (aref slots (+ b 1)))
           (meta (aref slots (+ b 2))) (record (aref slots (+ b 4)))
           (ctrl (aref (frammento-ctrl f) s)) (arena (frammento-arena f))
           (match (and (= ctrl (impronta h)) (= 1 (ldb (byte 8 48) meta))
                       (zerop (ldb (byte 8 56) meta)) (zerop (ldb (byte 32 32) record))
                       (stessa-chiave-p chiave arena (ldb (byte 32 0) meta)
                                       (ldb (byte 16 32) meta)))))
      (when dopo-campi (funcall dopo-campi f s))
      (sb-thread:barrier (:read))
      (if (/= seq (aref slots (+ b 3))) (values 0 0 0 :retry)
          (values csn loc (ldb (byte 32 0) record) (if match :hit :skip))))))
(declaim (ftype (function (frammento ottetti u64 (or null function))
                         (values u64 u64 u32 keyword)) sonda-reader))
(defun sonda-reader (f chiave h dopo-campi)
  "Al più C controlli per tentativo, nessuna ricorsione o lock."
  (dotimes (g (/ (frammento-capacita f) +gruppo+) (values 0 0 0 :miss))
    (dotimes (n +gruppo+)
      (let* ((s (posizione h (frammento-capacita f) (+ (* g +gruppo+) n)))
             (ctrl (aref (frammento-ctrl f) s)))
        (when (= ctrl +vuoto+) (return-from sonda-reader (values 0 0 0 :miss)))
        (when (= ctrl (impronta h))
          (multiple-value-bind (csn loc len stato) (leggi-slot f s chiave h dopo-campi)
            (unless (eq stato :skip) (return-from sonda-reader (values csn loc len stato)))))))))
(declaim (ftype (function (indice ottetti &key (:attempts integer)
                         (:after-fragment (or null function)) (:after-fields (or null function)))
                         (values u64 u64 u32 keyword fixnum)) leggi))
(defun leggi (i chiave &key (attempts 8) after-fragment after-fields)
  "Valori CSN, location u64, record-len u32, :hit/:miss/:retry-limit, tentativi scartati.
Gli hook sono del solo harness; :retry-limit richiede inoltro al writer dal chiamante."
  (check-type i indice)
  (valida-chiave i chiave)
  (intero-limitato attempts 1 8)
  (check-type after-fragment (or null function))
  (check-type after-fields (or null function))
  (let ((h (hash-chiave chiave)))
    (dotimes (tentativo attempts (values 0 0 0 :retry-limit attempts))
      (let* ((root (indice-root i)) (gen (radice-generazione root)))
        (sb-thread:barrier (:read))
        (let ((f (radice-frammento root)))
          (when after-fragment (funcall after-fragment f))
          (multiple-value-bind (csn loc len stato) (sonda-reader f chiave h after-fields)
            (sb-thread:barrier (:read))
            (let ((attuale (indice-root i)))
              (when (and (not (eq stato :retry)) (eq root attuale)
                         (= gen (radice-generazione attuale)))
                (return-from leggi (values csn loc len stato tentativo))))))))))

(declaim (ftype (function (integer) double-float) secondi))
(defun secondi (ticks)
  "Conversione per reporting, fuori dal kernel di hashing."
  (/ (coerce ticks 'double-float) internal-time-units-per-second))
(declaim (ftype (function (indice) list) statistiche))
(defun statistiche (i)
  "Snapshot del writer; nessuna sincronizzazione dei contatori per i reader."
  (let* ((root (indice-root i)) (f (radice-frammento root)))
    (list :capacity (frammento-capacita f) :documents (frammento-vivi f)
          :ctrl-bytes (length (frammento-ctrl f)) :slot-words (length (frammento-slots f))
          :bytes-per-slot +byte-slot+ :arena-used (frammento-usati f)
          :arena-capacity (length (frammento-arena f)) :live-key-bytes (frammento-byte-vivi f)
          :tombstones (frammento-morti f) :root-generation (radice-generazione root)
          :payload-bytes (payload f) :peak-payload-bytes (indice-picco-payload i)
          :peak-transient-bytes (indice-picco-transitorio i)
          :insertions (indice-inserimenti i) :updates (indice-aggiornamenti i)
          :deletions (indice-eliminazioni i) :rebuilds (indice-rebuild i)
          :arena-growths (indice-crescite i) :copied-key-bytes (indice-byte-copiati i)
          :max-copied-key-bytes (indice-max-byte-copiati i)
          :max-source-slots-visited (indice-max-slot-visitati i)
          :max-source-slots-copied (indice-max-slot-copiati i)
          :max-directory-references-copied (indice-max-riferimenti i)
          :max-preparation-seconds (secondi (indice-max-preparazione-ticks i))
          :limits (list :key-bytes (indice-max-chiave i) :document-bytes (indice-max-documento i)
                        :arena-bytes (indice-max-arena i) :copy-bytes (indice-budget-copia i)
                        :transient-bytes (indice-budget-transitorio i)
                        :maintenance-seconds (secondi (indice-budget-ticks i))
                        :reader-attempts 8 :load-factor 7/8)
          :time-budget :cooperative-wall :memory-accounting :array-payload
          :pending '(:split :extendible-directory :retained-versions :writer-fallback
                     :memory-model-arm64-x86-64 :retired-roots-rss-budget))))

;;;; Harness bounded, separato dal percorso caldo e dall'oracolo del codec.
(declaim (ftype (function (fixnum u64) ottetti) chiave-fixture))
(defun chiave-fixture (len id)
  "Prefisso binario deterministico, ID nei byte finali; len configurato dal test."
  (let ((chiave (make-array len :element-type '(unsigned-byte 8))))
    (dotimes (n len) (setf (aref chiave n) (logand 255 (+ 113 (* 17 n)))))
    (dotimes (n (min len 8))
      (setf (aref chiave (- len n 1)) (ldb (byte 8 (* n 8)) id)))
    chiave))
(declaim (ftype (function (ottetti) u64) hash-riferimento))
(defun hash-riferimento (chiave)
  "Oracolo aritmetico indipendente; intermedi integer, MOD anziché maschera."
  (let ((h #xcbf29ce484222325))
    (dotimes (n (length chiave) h)
      (setf h (mod (* (logxor h (aref chiave n)) #x100000001b3) (expt 2 64))))))
(declaim (ftype (function (ottetti fixnum) u32) hash-loop))
(defun hash-loop (chiave volte)
  "Kernel inline per misurare le allocazioni degli intermedi, sink u32."
  (declare (type ottetti chiave) (type fixnum volte))
  (let ((sink 0))
    (declare (type u32 sink))
    (dotimes (n volte sink)
      (setf sink (logxor sink (ldb (byte 32 0) (hash-chiave chiave)))))))
(declaim (ftype (function (indice) list) fotografia))
(defun fotografia (i)
  "Identità root/array e copie integrali, compresi byte non referenziati e contatori."
  (let* ((r (indice-root i)) (f (radice-frammento r)) (a (frammento-arena f)))
    (list r f a (copy-seq (frammento-ctrl f)) (copy-seq (frammento-slots f))
          (copy-seq a) (statistiche i))))
(declaim (ftype (function (indice function keyword) null) verifica-rifiuto))
(defun verifica-rifiuto (i azione motivo)
  "Ogni rifiuto confronta identità e contenuti dello stato completo."
  (let ((prima (fotografia i))
        (esito (handler-case (progn (funcall azione) :nessun-rifiuto)
                 (limite-indice (c) (limite-motivo c))
                 (type-error () :type-error))))
    (assert (eq esito motivo))
    (let ((dopo (fotografia i)))
      (dotimes (n 3) (assert (eq (nth n prima) (nth n dopo))))
      (assert (equalp (nthcdr 3 prima) (nthcdr 3 dopo)))))
  nil)
(declaim (ftype (function (indice ottetti u64 u64 u32) null) verifica-entry))
(defun verifica-entry (i chiave csn loc len)
  "Controlla tutti i campi della risposta senza ridurre il CSN a fixnum."
  (multiple-value-bind (c l n stato scartati) (leggi i chiave)
    (assert (eq stato :hit)) (assert (= c csn)) (assert (= l loc))
    (assert (= n len)) (assert (zerop scartati)))
  nil)
(declaim (ftype (function (indice ottetti u64) boolean) inserisci-fixture))
(defun inserisci-fixture (i chiave valore)
  "Pattern coerente, location alta; documento fixture di un byte."
  (inserisci i chiave valore #xffffffff (ldb (byte 32 0) valore)
             (+ +header+ (length chiave) 1)))
(declaim (ftype (function (function indice ottetti t t t t) t) invoca-dati-errati))
(defun invoca-dati-errati (fun i chiave csn segmento off len)
  "Confine dinamico del test: i dati invalidi esercitano i typecheck a runtime."
  (funcall fun i chiave csn segmento off len))

;;; REQ: REQ-LIM-001 REQ-LIM-003
(declaim (ftype (function () list) test-req-lim-001-layout))
(defun test-req-lim-001-layout ()
  "Confini di chiave/record, packing, u64 alto e configurazione ridotta."
  (let ((i (make-indice :capacity 16)) (len-record 0))
    (assert (zerop (getf (statistiche i) :arena-capacity)))
    (dolist (len '(1 255 256 65535))
      (let* ((k (chiave-fixture len 42)) (record (+ +header+ len +documento-max+)))
        (assert (inserisci i k +mask64+ #xffffffff #xffffffff record))
        (verifica-entry i k +mask64+ +mask64+ record)
        (verifica-rifiuto i (lambda () (inserisci i k 1 1 1 (1+ record))) :lunghezza-record)
        (setf len-record record)))
    (assert (= len-record +record-max+))
    (dolist (len '(0 65536))
      (let ((k (chiave-fixture len 1)))
        (verifica-rifiuto i (lambda () (inserisci-fixture i k 1)) :lunghezza-chiave)
        (verifica-rifiuto i (lambda () (leggi i k)) :lunghezza-chiave)))
    (let ((k (chiave-fixture 1 42)))
      (dolist (csn (list -1 (1+ +mask64+)))
        (verifica-rifiuto i (lambda () (invoca-dati-errati (symbol-function 'inserisci)
                                                        i k csn 0 0 25)) :type-error))
      (dolist (x '(-1 4294967296))
        (verifica-rifiuto i (lambda () (invoca-dati-errati (symbol-function 'inserisci)
                                                        i k 1 x 0 25)) :type-error)
        (verifica-rifiuto i (lambda () (invoca-dati-errati (symbol-function 'inserisci)
                                                        i k 1 0 x 25)) :type-error)
        (verifica-rifiuto i (lambda () (invoca-dati-errati (symbol-function 'inserisci)
                                                        i k 1 0 0 x)) :type-error))
      (verifica-rifiuto i (lambda () (inserisci i k 1 0 0 #xffffffff)) :lunghezza-record)
      (verifica-rifiuto i (lambda () (inserisci i k 1 0 0 24)) :lunghezza-record))
    (let ((f (radice-frammento (indice-root i))))
      (assert (= (* 5 16) (length (frammento-slots f))))
      (dotimes (s 16)
        (when (< (aref (frammento-ctrl f) s) 128)
          (assert (zerop (ldb (byte 8 56) (aref (frammento-slots f) (+ (* s 5) 2)))))
          (assert (zerop (ldb (byte 32 32) (aref (frammento-slots f) (+ (* s 5) 4))))))))
    (let ((m (metadata #xffffffff #xffff #xff)))
      (assert (= m #x00ffffffffffffff))
      (assert (= #xffffffff (ldb (byte 32 0) m)))
      (assert (= #xffff (ldb (byte 16 32) m))))
    (let* ((ridotto (make-indice :capacity 8 :max-key-bytes 255 :max-document-bytes 1))
           (k (chiave-fixture 255 1)))
      (assert (inserisci-fixture ridotto k 1))
      (verifica-rifiuto ridotto (lambda () (inserisci ridotto k 2 1 1 (+ 24 255 2)))
                        :lunghezza-record)
      (verifica-rifiuto ridotto (lambda () (inserisci-fixture ridotto (chiave-fixture 256 1) 1))
                        :lunghezza-chiave))
    (list :status :ok :accepted-key-lengths '(1 255 256 65535)
          :rejected-key-lengths '(0 65536) :max-record-bytes len-record
          :max-document-bytes +documento-max+ :bytes-per-slot +byte-slot+
          :documents-tested 4 :statistics (statistiche i))))

;;; REQ: REQ-LIM-003
(declaim (ftype (function () list) test-req-lim-003-hash))
(defun test-req-lim-003-hash ()
  "Golden conosciuti e confronto aritmetico lungo, senza semantica di stringhe."
  (let ((a (make-array 1 :element-type '(unsigned-byte 8) :initial-element 97))
        (foobar (make-array 6 :element-type '(unsigned-byte 8)
                             :initial-contents '(102 111 111 98 97 114)))
        (vuota (make-array 0 :element-type '(unsigned-byte 8))))
    (assert (= +seed+ (hash-chiave vuota)))
    (assert (= #xaf63dc4c8601ec8c (hash-chiave a)))
    (assert (= #x85944171f73967e8 (hash-chiave foobar))))
  (let ((golden nil))
    (dolist (len '(1 16 255 256 65535))
      (let ((k (chiave-fixture len 424242)))
        (assert (= (hash-chiave k) (hash-riferimento k)))
        (push (list :key-bytes len :hash (hash-chiave k)) golden)))
    (let ((k (chiave-fixture 256 17)))
      (hash-loop k 32)
      (let* ((prima (sb-ext:get-bytes-consed)) (sink (hash-loop k 256))
             (allocati (- (sb-ext:get-bytes-consed) prima)))
        (assert (zerop sink))
        (list :status :ok :seed +seed+ :known-golden-count 3
              :differential-hash-count 5 :hash-fixtures (nreverse golden)
              :kernel-iterations 256 :kernel-bytes-consed allocati)))))
(declaim (ftype (function () list) test-req-lim-003-confronto))
(defun test-req-lim-003-confronto ()
  "Chiavi a prefisso comune e impronta uguale richiedono confronto esatto."
  (let* ((i (make-indice :capacity 8)) (a (chiave-fixture 32 0))
         (b (copy-seq a)) (originale (copy-seq a)) (prove 0))
    (loop for n from 1 to 65535 do
      (setf (aref b 30) (ldb (byte 8 8) n) (aref b 31) (ldb (byte 8 0) n))
      (incf prove)
      (when (= (impronta (hash-chiave a)) (impronta (hash-chiave b))) (return)))
    (assert (not (equalp a b)))
    (assert (= (impronta (hash-chiave a)) (impronta (hash-chiave b))))
    (assert (inserisci-fixture i a 1)) (assert (inserisci-fixture i b 2))
    (fill a 0)
    (verifica-entry i originale 1 #xffffffff00000001 57)
    (verifica-entry i b 2 #xffffffff00000002 57)
    (assert (eq :miss (nth-value 3 (leggi i a))))
    (assert (elimina i originale))
    (verifica-entry i b 2 #xffffffff00000002 57)
    (list :status :ok :fingerprint-searches prove :prefix-bytes 30
          :private-copy-tested t :full-comparison-tested t)))

;;; REQ: REQ-LIM-003 REQ-IDX-005 REQ-IDX-007
(declaim (ftype (function () list) test-req-lim-003-budget))
(defun test-req-lim-003-budget ()
  "Rifiuti di arena, memoria, byte di migrazione e tempo lasciano lo stato identico."
  (let* ((k (chiave-fixture 16 1)) (altro (chiave-fixture 16 2))
         (arena (make-indice :capacity 8 :max-arena-bytes 31))
         (copie (make-indice :capacity 8 :copy-byte-budget 31))
         (memoria (make-indice :capacity 8 :transient-byte-budget 384)))
    (assert (inserisci-fixture arena k 1))
    (verifica-rifiuto arena (lambda () (inserisci-fixture arena altro 2)) :arena)
    (verifica-rifiuto copie (lambda () (inserisci-fixture copie k 1)) :byte-copiati)
    (assert (inserisci-fixture memoria k 1))
    (assert (inserisci-fixture memoria altro 2))
    (verifica-rifiuto memoria
                      (lambda () (inserisci-fixture memoria (chiave-fixture 16 3) 3))
                      :memoria-transitoria)
    (verifica-rifiuto memoria (lambda () (ricostruisci memoria (indice-root memoria) -1))
                      :memoria-transitoria))
  (let ((i (make-indice :capacity 8 :copy-byte-budget 128)))
    (dotimes (n 4) (assert (inserisci-fixture i (chiave-fixture 16 n) (1+ n))))
    (dotimes (n 2) (assert (elimina i (chiave-fixture 16 n))))
    (verifica-rifiuto i (lambda () (inserisci-fixture i (chiave-fixture 64 99) 99))
                      :byte-copiati)
    (assert (zerop (indice-rebuild i))))
  (let* ((arme nil) (ticks 0)
         (i (make-indice :capacity 8 :maintenance-seconds
                         (/ 3 internal-time-units-per-second)
                         :clock (lambda () (prog1 ticks (when arme (incf ticks))))))
         (k (chiave-fixture 4 1)))
    (assert (inserisci-fixture i k 1))
    (setf arme t ticks 0)
    (verifica-rifiuto i (lambda () (inserisci-fixture i (chiave-fixture 4 2) 2))
                      :tempo-preparazione)
    (assert (= ticks 4)))
  (list :status :ok :rejection-snapshots 7
        :exhausted '(:arena :copy-bytes :transient-bytes :rebuild-copy-bytes :wall-time)
        :time-fixture-clock-reads 4 :production-commit nil))
(declaim (ftype (function () list) test-req-idx-005-churn))
(defun test-req-idx-005-churn ()
  "Saturazione degli slot e 64 cicli di recupero senza crescita illimitata."
  (let ((i (make-indice :capacity 8)))
    (dotimes (n 7) (assert (inserisci-fixture i (chiave-fixture 8 n) (1+ n))))
    (verifica-rifiuto i (lambda () (inserisci-fixture i (chiave-fixture 8 7) 8))
                      :capacita-frammento)
    (assert (not (inserisci-fixture i (chiave-fixture 8 0) +mask64+)))
    (verifica-entry i (chiave-fixture 8 0) +mask64+ +mask64+ 33))
  (let ((i (make-indice :capacity 16 :max-arena-bytes 512)))
    (dotimes (ciclo 64)
      (dotimes (n 6)
        (assert (inserisci-fixture i (chiave-fixture 16 (+ n (* ciclo 6))) (1+ n))))
      (dotimes (n 6) (assert (elimina i (chiave-fixture 16 (+ n (* ciclo 6))))))
      (assert (zerop (frammento-vivi (radice-frammento (indice-root i))))))
    (ricostruisci i (indice-root i) -1)
    (let ((f (radice-frammento (indice-root i))))
      (assert (zerop (frammento-usati f))) (assert (zerop (frammento-morti f)))
      (assert (zerop (length (frammento-arena f)))))
    (assert (plusp (indice-rebuild i)))
    (assert (<= (indice-max-slot-visitati i) 16))
    (assert (<= (indice-max-byte-copiati i) (indice-budget-copia i)))
    (assert (<= (indice-picco-transitorio i) (indice-budget-transitorio i)))
    (list :status :ok :cycles 64 :insertions 384 :deletions 384
          :statistics (statistiche i))))

;;; REQ: REQ-IDX-003 REQ-IDX-007
(declaim (ftype (function () list) test-req-idx-003-seqlock))
(defun test-req-idx-003-seqlock ()
  "Aggiornamento fra campi e contatore, contatore dispari e rotazione vicino alla soglia."
  (let* ((i (make-indice :capacity 8)) (k (chiave-fixture 16 1)) (una-volta nil))
    (assert (inserisci-fixture i k 1))
    (multiple-value-bind (csn loc len stato scartati)
        (leggi i k :after-fields (lambda (f s) (assert (frammento-p f)) (assert (>= s 0))
                                  (unless una-volta (setf una-volta t)
                                          (assert (not (inserisci-fixture i k 2))))))
      (assert (= csn 2)) (assert (= loc #xffffffff00000002))
      (assert (= len 41)) (assert (eq stato :hit)) (assert (= scartati 1)))
    (let* ((f (radice-frammento (indice-root i))) (s (cerca-writer f k (hash-chiave k)))
           (slots (frammento-slots f)) (pos (+ (* s 5) 3)) (seq (aref slots pos)))
      (setf (aref slots pos) (1+ seq))
      (unwind-protect
           (dolist (n '(1 8))
             (multiple-value-bind (csn loc len stato scartati) (leggi i k :attempts n)
               (assert (zerop csn)) (assert (zerop loc)) (assert (zerop len))
               (assert (eq stato :retry-limit)) (assert (= scartati n))))
        (setf (aref slots pos) seq))
      (setf (aref slots pos) (- +soglia-seq+ 2))
      (assert (not (inserisci-fixture i k 3)))
      (assert (= (indice-rebuild i) 1))
      (verifica-entry i k 3 #xffffffff00000003 41))
    (let ((valore 3))
      (assert (eq :retry-limit
                  (nth-value 3 (leggi i k :after-fields
                                     (lambda (f s) (assert (frammento-p f)) (assert (>= s 0))
                                       (incf valore) (inserisci-fixture i k valore))))))
      (assert (= valore 11)))
    (verifica-rifiuto i (lambda () (leggi i k :attempts 9)) :type-error)
    (verifica-rifiuto i (lambda () (leggi i k :attempts 0)) :type-error)
    (list :status :ok :odd-counter-attempts '(1 8) :field-race-retries 1
          :continuous-update-attempts 8 :threshold-rebuilds 1)))
(declaim (ftype (function () list) test-req-idx-007-root))
(defun test-req-idx-007-root ()
  "Scarta hit e miss della root ritirata e limita i cambiamenti ripetuti della root."
  (let* ((i (make-indice :capacity 8)) (k (chiave-fixture 16 1))
         (nuova (chiave-fixture 16 2)) (una-volta nil) (ritirato nil))
    (assert (inserisci-fixture i k 1))
    (multiple-value-bind (csn loc len stato scartati)
        (leggi i k :after-fragment
               (lambda (f) (unless una-volta
                             (setf una-volta t ritirato f)
                             (inserisci-fixture i k 2)
                             (ricostruisci i (indice-root i) -1)
                             (inserisci-fixture i k 3))))
      (assert (= csn 3)) (assert (= loc #xffffffff00000003))
      (assert (= len 41)) (assert (eq stato :hit)) (assert (= scartati 1)))
    (assert (= 2 (nth-value 0 (sonda-reader ritirato k (hash-chiave k) nil))))
    (setf una-volta nil)
    (multiple-value-bind (csn loc len stato scartati)
        (leggi i nuova :after-fragment
               (lambda (f) (assert (frammento-p f))
                 (unless una-volta (setf una-volta t)
                         (ricostruisci i (indice-root i) -1)
                         (inserisci-fixture i nuova 4))))
      (assert (= csn 4)) (assert (= loc #xffffffff00000004))
      (assert (= len 41)) (assert (eq stato :hit)) (assert (= scartati 1)))
    (multiple-value-bind (csn loc len stato scartati)
        (leggi i k :after-fragment (lambda (f) (assert (frammento-p f))
                                    (ricostruisci i (indice-root i) -1)))
      (assert (zerop csn)) (assert (zerop loc)) (assert (zerop len))
      (assert (eq stato :retry-limit)) (assert (= scartati 8)))
    (let* ((r (indice-root i)) (f (radice-frammento r))
           (s (cerca-writer f k (hash-chiave k))))
      (setf (indice-root i) (%radice +mask64+ f)
            (aref (frammento-slots f) (+ (* s 5) 3)) (- +soglia-seq+ 2))
      (verifica-rifiuto i (lambda () (inserisci-fixture i k 5)) :generazione-root))
    (list :status :ok :retired-hit-retries 1 :retired-miss-retries 1
          :continuous-root-attempts 8 :generation-wrap-rejected t)))

;;; REQ: REQ-LIM-003 REQ-IDX-003 REQ-IDX-005
(declaim (ftype (function (indice ottetti hash-table) null) verifica-oracolo))
(defun verifica-oracolo (i k riferimento)
  "L'oracolo equalp confronta CSN, location e lunghezza dopo ogni operazione."
  (multiple-value-bind (atteso presente) (gethash k riferimento)
    (multiple-value-bind (csn loc len stato scartati) (leggi i k)
      (assert (zerop scartati))
      (if presente
          (progn (assert (eq stato :hit))
                 (assert (equalp atteso (list csn loc len))))
          (progn (assert (eq stato :miss)) (assert (zerop csn))
                 (assert (zerop loc)) (assert (zerop len))))))
  nil)
(declaim (ftype (function () list) test-req-idx-005-differenziale))
(defun test-req-idx-005-differenziale ()
  "600 operazioni, seed fisso, 64 chiavi con quattro lunghezze e CSN alti."
  (let ((i (make-indice :capacity 128)) (riferimento (make-hash-table :test 'equalp))
        (chiavi (make-array 64)) (seed 424242) (scritture 0) (eliminazioni 0) (letture 0))
    (dotimes (n 64)
      (setf (aref chiavi n) (chiave-fixture (nth (mod n 4) '(1 255 256 65535)) n)))
    (dotimes (passo 600)
      (setf seed (logand #xffffffff (+ (* seed 1664525) 1013904223)))
      (let* ((k (aref chiavi (ldb (byte 6 16) seed)))
             (operazione (mod seed 3)) (presente (nth-value 1 (gethash k riferimento))))
        (case operazione
          (0 (let* ((csn (- +mask64+ passo)) (seg (- #xffffffff passo))
                    (off (+ passo 7)) (len (+ 24 (length k) (mod passo 100))))
               (assert (eq (inserisci i k csn seg off len) (not presente)))
               (setf (gethash (copy-seq k) riferimento) (list csn (logior (ash seg 32) off) len))
               (incf scritture)))
          (1 (assert (eq (elimina i k) presente)) (remhash k riferimento) (incf eliminazioni))
          (2 (incf letture))
          (otherwise (rifiuta :invariante-fixture)))
        (verifica-oracolo i k riferimento)
        (assert (= (hash-table-count riferimento)
                   (frammento-vivi (radice-frammento (indice-root i)))))))
    (dotimes (n 64) (verifica-oracolo i (aref chiavi n) riferimento))
    (list :status :ok :seed 424242 :operations 600 :oracle-comparisons 664
          :write-requests scritture :delete-requests eliminazioni :read-requests letture
          :key-lengths '(1 255 256 65535) :statistics (statistiche i))))

(declaim (ftype (function () list) check))
(defun check ()
  "Suite corta bounded: restituisce conteggi e limiti; un errore non ritorna :ok."
  (let* ((inizio (get-internal-real-time))
         (risultati (list (test-req-lim-001-layout) (test-req-lim-003-hash)
                          (test-req-lim-003-confronto) (test-req-lim-003-budget)
                          (test-req-idx-005-churn) (test-req-idx-003-seqlock)
                          (test-req-idx-007-root) (test-req-idx-005-differenziale))))
    (list :status :ok :module :indice :format-version 2 :test-groups (length risultati)
          :differential-operations 600 :oracle-comparisons 664 :churn-cycles 64
          :limits (list :document-bytes +documento-max+ :key-bytes +chiave-max+
                        :max-record-bytes +record-max+ :slot-words +parole-slot+
                        :bytes-per-slot +byte-slot+ :reader-attempts 8
                        :check-capacity-max 128 :check-differential-keys 64
                        :copy-block-bytes +blocco+ :arena-growth-steps 33)
          :seconds (secondi (- (get-internal-real-time) inizio)) :tests risultati
          :pending '(:split :extendible-directory :retained-versions :writer-fallback
                     :memory-model-arm64-x86-64 :production-commit :v2-gate))))

;;;; Benchmark solo su richiesta del parent: limiti complessivi cooperativi.
(declaim (ftype (function (ottetti u64) null) cambia-id))
(defun cambia-id (chiave id)
  "Riusa il buffer della fixture; ultimi otto byte little endian dal fondo."
  (declare (type ottetti chiave) (type u64 id))
  (dotimes (n 8) (setf (aref chiave (- (length chiave) n 1)) (ldb (byte 8 (* n 8)) id)))
  nil)
(declaim (ftype (function (indice ottetti fixnum integer) fixnum) bench-inserimenti))
(defun bench-inserimenti (i chiave massimo scadenza)
  "Conta soltanto gli inserimenti terminati; termine globale prima di ogni operazione."
  (let ((completati 0))
    (dotimes (n massimo completati)
      (when (>= (get-internal-real-time) scadenza) (return completati))
      (cambia-id chiave n)
      (assert (inserisci-fixture i chiave (1+ n)))
      (incf completati))))
(declaim (ftype (function (indice ottetti fixnum integer)
                         (values fixnum fixnum fixnum u32)) bench-letture-modifiche))
(defun bench-letture-modifiche (i chiave documenti scadenza)
  "Letture, aggiornamenti e churn bounded; durata e conteggi effettivi esterni."
  (let ((letture 0) (aggiornamenti 0) (churn 0) (sink 0))
    (declare (type u32 sink))
    (dotimes (n documenti)
      (when (>= (get-internal-real-time) scadenza) (return))
      (cambia-id chiave n)
      (multiple-value-bind (csn loc len stato scartati) (leggi i chiave)
        (assert (eq stato :hit)) (assert (zerop scartati))
        (assert (= loc (logior #xffffffff00000000 (1+ n))))
        (assert (= len (+ +header+ (length chiave) 1)))
        (setf sink (logxor sink (ldb (byte 32 0) csn))))
      (incf letture))
    (dotimes (n documenti)
      (when (>= (get-internal-real-time) scadenza) (return))
      (cambia-id chiave n)
      (assert (not (inserisci-fixture i chiave (+ 1 documenti n))))
      (incf aggiornamenti))
    (dotimes (n (min documenti 64))
      (when (>= (get-internal-real-time) scadenza) (return))
      (cambia-id chiave n)
      (assert (elimina i chiave))
      ;; Il reinserimento fa parte della stessa iterazione bounded di churn.
      (assert (inserisci-fixture i chiave (+ 1 (* 2 documenti) n)))
      (incf churn))
    (values letture aggiornamenti churn sink)))
(declaim (ftype (function (fixnum fixnum fixnum integer) list) bench-caso))
(defun bench-caso (len massimo capacita scadenza)
  "Un frammento dimensionato per il carico; niente split nascosti nel benchmark."
  (let* ((inizio (get-internal-real-time)) (allocazioni (sb-ext:get-bytes-consed))
         (i (make-indice :capacity capacita :max-arena-bytes 16777216
                         :copy-byte-budget 16777216
                         :transient-byte-budget +memoria-bench-max+))
         (chiave (chiave-fixture len 0))
         (inseriti (bench-inserimenti i chiave massimo scadenza)))
    (multiple-value-bind (letture aggiornamenti churn sink)
        (bench-letture-modifiche i chiave inseriti scadenza)
      (list :status :ok :key-bytes len :requested-documents massimo :inserted-documents inseriti
            :read-operations letture :update-operations aggiornamenti :churn-cycles churn
            :operations (+ inseriti letture aggiornamenti (* 2 churn)) :sink sink
            :seconds (secondi (- (get-internal-real-time) inizio))
            :bytes-consed (- (sb-ext:get-bytes-consed) allocazioni)
            :statistics (statistiche i)))))
(declaim (ftype (function (&key (:seconds real)) list) benchmark))
(defun benchmark (&key (seconds 3))
  "Massimi 10000/1000/64 documenti, chiavi16/256/65535, budget globale <=3s cooperativo.
Restituisce i conteggi misurati; nessuna stima di throughput o gate di produzione."
  (unless (typep seconds '(real 0 3))
    (error 'type-error :datum seconds :expected-type '(real 0 3)))
  (let* ((inizio (get-internal-real-time))
         (scadenza (+ inizio (floor (* seconds internal-time-units-per-second))))
         (casi (list (bench-caso 16 10000 16384 scadenza)
                     (bench-caso 256 1000 2048 scadenza)
                     (bench-caso 65535 64 128 scadenza)))
         (durata (secondi (- (get-internal-real-time) inizio))))
    (list :status :ok :module :indice :cases casi :seconds durata
          :operations (loop for caso in casi sum (getf caso :operations))
          :limits (list :seconds seconds :time-budget :cooperative-wall
                        :key-bytes '(16 256 65535) :documents '(10000 1000 64)
                        :transient-bytes +memoria-bench-max+ :capacity-max 16384)
          :deadline-overrun-seconds (max 0d0 (- durata (coerce seconds 'double-float)))
          :memory-accounting :array-payload :split-implemented nil
          :production-commit nil :v2-gate-completed nil)))
