(in-package #:arcdocdb.wal.tests)

(deftest test-REQ-WAL-002-two-lots-one-flush-and-reuse
  (let* ((output (buffer 4096)) (pos 0) (flushes 0)
         (file (fixture-file :writer (lambda (fd data start count)
                                       (declare (ignore fd))
                                       (let ((n (min 7 count)))
                                         (replace output data :start1 pos :start2 start :end2 (+ start n))
                                         (incf pos n) n))
                             :flush (lambda (fd) (declare (ignore fd)) (incf flushes) 0)))
         (log (crea-log-io file :segment 31)) (a (fixture-lotto))
         (b (fixture-lotto :start (lunghezza-lotto a))) (group (fixture-group log a b)))
    (is (= (scrivi-gruppo group) (+ (lunghezza-lotto a) (lunghezza-lotto b))))
    (is (zerop flushes)) (is (coperto-p a :async)) (is (not (coperto-p a :group)))
    (signals invalid-argument (riusa-gruppo group))
    (signals invalid-argument (riusa-lotto a))
    (is (= pos (sincronizza-gruppo group))) (is (= flushes 1))
    (is (coperto-p a :group)) (is (coperto-p b :strong))
    (signals invalid-argument (sincronizza-gruppo group))
    (signals invalid-argument (riusa-lotto a))
    (multiple-value-bind (end state batches records)
        (arcdocdb.recovery.scan:scansiona-log output 0 pos 31 :file-size pos :version 2)
      (is (= end pos)) (is (eq state :complete)) (is (= batches 2)) (is (= records 2)))
    (let ((old-buffer (arcdocdb.wal::lotto-buffer a)))
      (riusa-gruppo group) (riusa-lotto a) (riusa-lotto b)
      (is (eq old-buffer (arcdocdb.wal::lotto-buffer a)))
      (sigilla-lotto a 20 pos pos)
      (aggiungi-lotto group a) (chiudi-gruppo group) (esegui-gruppo group)
      (is (= flushes 2)))
    (arcdocdb.io:chiudi file)))

(deftest test-REQ-AFF-008-group-budget-identity-and-order
  (let* ((file (fixture-file)) (log (crea-log-io file :segment 31))
         (a (fixture-lotto)) (group (crea-gruppo log :max-lots 1 :max-bytes 82)))
    (signals invalid-argument (chiudi-gruppo group))
    (signals invalid-argument (aggiungi-lotto group (fixture-lotto :file-id 32)))
    (signals invalid-argument (aggiungi-lotto group (fixture-lotto :version 1)))
    (signals invalid-argument (aggiungi-lotto group (fixture-lotto :kind :control :file-id 0)))
    (aggiungi-lotto group a)
    (signals invalid-argument (aggiungi-lotto group (fixture-lotto :start 83)))
    (signals resource-exhausted (aggiungi-lotto group (fixture-lotto :start 82)))
    (signals invalid-argument (aggiungi-lotto (crea-gruppo log) a))
    (chiudi-gruppo group)
    (signals invalid-argument (aggiungi-lotto group a))
    (dolist (args '((:max-lots 0) (:max-lots 1025) (:max-bytes 55) (:max-bytes 67108865)))
      (signals invalid-argument (apply #'crea-gruppo log args)))
    (arcdocdb.io:chiudi file)))

(deftest test-REQ-AFF-008-file-budget-before-any-write
  (dolist (config '((:max-transfer 81) (:max-file-bytes 81) (:max-file-bytes 163)))
    (let* ((calls 0) (file (apply #'fixture-file :writer
                                (lambda (fd b start count) (declare (ignore fd b start)) (incf calls) count)
                                config))
           (log (crea-log-io file :segment 31)) (a (fixture-lotto))
           (group (fixture-group log a (fixture-lotto :start 82))))
      (signals resource-exhausted (scrivi-gruppo group))
      (is (zerop calls)) (is (eq :ready (stato-gruppo group)))
      (is (null (arcdocdb.wal::log-io-active log)))
      (is (eq :open (stato-log log))) (arcdocdb.io:chiudi file))))

(deftest test-REQ-WAL-005-offset-and-durable-witness-before-write
  (let* ((calls 0) (file (fixture-file :writer (lambda (fd b start count)
                                              (declare (ignore fd b start)) (incf calls) count)))
         (log (crea-log-io file :segment 31)))
    (dolist (lotto (list (fixture-lotto :start 1) (fixture-lotto)))
      (when (= (arcdocdb.wal:inizio-lotto lotto) 0)
        ;; Mutazione privata C4: anche una frontiera SEAL falsa è rifiutata prima di write.
        (arcdocdb.binary:scrivi-u64 (arcdocdb.wal::lotto-buffer lotto)
                                  (- (lunghezza-lotto lotto) 16) 1))
      (let ((group (fixture-group log lotto)))
        (signals invalid-argument (scrivi-gruppo group))
        (is (null (arcdocdb.wal::log-io-active log)))
        (is (eq :ready (stato-gruppo group)))))
    (is (zerop calls)) (arcdocdb.io:chiudi file)))

(deftest test-REQ-WAL-003-control-log-never-async
  (dolist (kind '(:control :multiserie))
    (let* ((file (fixture-file)) (log (crea-log-io file kind 0))
           (lotto (fixture-lotto :kind kind :file-id 0)) (group (fixture-group log lotto)))
      (signals invalid-argument (coperto-p lotto :async))
      (scrivi-gruppo group) (is (not (coperto-p lotto :strong)))
      (sincronizza-gruppo group) (is (coperto-p lotto :strong))
    (arcdocdb.io:chiudi file))))

(deftest test-REQ-AFF-008-cancel-unsent-group-releases-capacity
  (let* ((file (fixture-file)) (log (crea-log-io file :segment 31))
         (lotto (fixture-lotto)) (group (fixture-group log lotto)))
    (annulla-gruppo group)
    (is (eq :sealed (stato-lotto lotto)))
    (is (eq :building (stato-gruppo group)))
    (aggiungi-lotto group lotto) (chiudi-gruppo group) (scrivi-gruppo group)
    (signals invalid-argument (annulla-gruppo group))
    (sincronizza-gruppo group) (riusa-gruppo group) (riusa-lotto lotto)
    (is (eq :open (stato-lotto lotto))) (arcdocdb.io:chiudi file)))
