(in-package #:arcdocdb.wal.tests)

(deftest test-REQ-WAL-002-native-group-and-durable-witness-v1-v2
  (dolist (version '(1 2))
    (arcdocdb.io.tests::with-directory (directory)
      (let* ((path (merge-pathnames "wal.tmp" directory)) (header (buffer 64))
             (serie (buffer 16)) (data (buffer 228)))
        (arcdocdb.storage.format:scrivi-header-segmento header 0 serie 31 0 :version version)
        (arcdocdb.io.tests::with-file (file (arcdocdb.io:crea-temporaneo path))
          (arcdocdb.io:append-esatto file header 0 64) (arcdocdb.io:durable-flush file)
          (let* ((log (crea-log-io file :segment 31 :version version))
                 (a (fixture-lotto :version version :start 64 :durable 64))
                 (b (fixture-lotto :version version :start 146 :durable 64)))
            (is (= 228 (esegui-gruppo (fixture-group log a b))))
            (is (coperto-p a :group)) (is (coperto-p b :strong))))
        (arcdocdb.io.tests::with-file (dir (arcdocdb.io:apri-directory directory))
          (arcdocdb.io:durable-flush dir))
        (arcdocdb.io.tests::with-file (file (arcdocdb.io:apri-lettura path))
          (arcdocdb.io:leggi-esatto file data 0 228 0))
        (multiple-value-bind (end actual-version)
            (arcdocdb.storage.format:verifica-header-segmento data 0 228 serie 31)
          (is (= 64 end)) (is (= version actual-version)))
        (multiple-value-bind (end state batches records)
            (arcdocdb.recovery.scan:scansiona-log data 64 228 31 :version version :file-size 228)
          (is (= end 228)) (is (eq state :complete)) (is (= batches 2)) (is (= records 2)))))))

(deftest test-REQ-AFF-009-subsequent-batch-witness-detects-old-corruption
  (dolist (version '(1 2))
    (let* ((output (buffer 4096)) (pos 0)
           (file (fixture-file :writer (lambda (fd data start count)
                                       (declare (ignore fd))
                                       (replace output data :start1 pos :start2 start :end2 (+ start count))
                                       (incf pos count) count)))
           (log (crea-log-io file :segment 31 :version version)))
      (esegui-gruppo (fixture-group log (fixture-lotto :version version)))
      (esegui-gruppo (fixture-group log (fixture-lotto :version version :start 82 :durable 82)))
      (setf (aref output 25) (logxor (aref output 25) 1))
      (signals arcdocdb.recovery.scan:log-corruption
               (arcdocdb.recovery.scan:scansiona-log output 0 pos 31 :version version :file-size pos))
      (arcdocdb.io:chiudi file))))
