;;; REQ: REQ-AFF-003 REQ-SIM-002 REQ-AFF-016 REQ-BEN-001
(in-package #:cl-user)
(declaim (optimize (safety 3) (speed 1) (debug 1)))

(defun spk02-integer-option (argomento prefisso minimo massimo)
  (let ((valore (parse-integer argomento :start (length prefisso) :junk-allowed nil)))
    (unless (<= minimo valore massimo) (error "Opzione fuori limite: ~A" argomento))
    valore))

(defun spk02-threads-option (testo)
  (loop with start = 0 for end = (position #\, testo :start start)
        for valore = (parse-integer testo :start start :end end :junk-allowed nil)
        collect valore while end do (setf start (1+ end))))

(defun spk02-options (argomenti)
  (let ((modo :bench) (esplicito nil) (opzioni nil))
    (dolist (argomento argomenti)
      (cond
        ((member argomento '("--check" "--bench") :test #'string=)
         (when esplicito (error "Modo duplicato."))
         (setf esplicito t modo (if (string= argomento "--check") :check :bench)))
        ((search "--live-mib=" argomento :end2 (min 11 (length argomento)))
         (setf (getf opzioni :live-bytes)
               (* 1048576 (spk02-integer-option argomento "--live-mib=" 1 512))))
        ((search "--threads=" argomento :end2 (min 10 (length argomento)))
         (setf (getf opzioni :thread-counts) (spk02-threads-option (subseq argomento 10))))
        ((search "--budget-ms=" argomento :end2 (min 12 (length argomento)))
         (setf (getf opzioni :budget-seconds)
               (/ (spk02-integer-option argomento "--budget-ms=" 1 15000) 1000)))
        ((search "--case-ms=" argomento :end2 (min 10 (length argomento)))
         (setf (getf opzioni :case-seconds)
               (/ (spk02-integer-option argomento "--case-ms=" 1 1000) 1000)))
        ((search "--forced-samples=" argomento :end2 (min 17 (length argomento)))
         (setf (getf opzioni :forced-samples)
               (spk02-integer-option argomento "--forced-samples=" 1 64)))
        (t (error "Argomento sconosciuto: ~A" argomento))))
    (when (and (eq modo :check) opzioni) (error "--check non accetta opzioni benchmark."))
    (values modo opzioni)))

(defun spk02-compila (radice)
  (let* ((core (merge-pathnames "core.lisp" radice))
         (fasl (merge-pathnames "out/core.fasl" radice))
         (*compile-verbose* nil) (*compile-print* nil))
    (ensure-directories-exist fasl)
    (handler-bind ((warning (lambda (c) (error "SPK02 compilazione: ~A" c))))
      (multiple-value-bind (prodotto avvisi fallimento) (compile-file core :output-file fasl)
        (unless (and prodotto (not avvisi) (not fallimento))
          (error "SPK02 compilazione fallita: ~A" core))))
    (load fasl :verbose nil :print nil)))

(defun spk02-main (radice)
  (multiple-value-bind (modo opzioni) (spk02-options (cdr sb-ext:*posix-argv*))
    (spk02-compila radice)
    (let ((check (funcall (symbol-function (find-symbol "CHECK" "ARCDOCDB.SPK02")))))
      (if (eq modo :check)
          (list :status :ok :spike :spk02 :mode :check :check check)
          (list :status :ok :spike :spk02 :mode :bench :check check
                :benchmark (apply (symbol-function (find-symbol "BENCHMARK" "ARCDOCDB.SPK02"))
                                  opzioni))))))

(let ((*read-eval* nil) (*print-readably* t) (*print-pretty* t)
      (*print-length* nil) (*print-level* nil) (*print-circle* t))
  (handler-case
      (let ((radice (make-pathname :name nil :type nil :defaults *load-truename*)))
        (write (spk02-main radice))
        (terpri)
        (finish-output))
    (error (c)
      (write (list :status :error :spike :spk02 :message (princ-to-string c)))
      (terpri)
      (finish-output)
      (sb-ext:exit :code 1))))
