;;;; Fase 0. Owner CHECK; vedere metodo-check-lettura-buffer.md prima di eseguire.
;;; REQ: REQ-IDX-001 REQ-IDX-007 REQ-VAL-001
(defpackage #:arcdocdb.spk01.check-lettura-buffer
  (:use #:cl)
  (:export #:check))
(in-package #:arcdocdb.spk01.check-lettura-buffer)
(declaim (optimize (safety 3) (speed 1) (debug 2)))

(defconstant +max64+ #xffffffffffffffff)
(defconstant +max24+ #xffffff)
(deftype destination () '(simple-array (unsigned-byte 64) (4)))
(define-condition check-failure (error)
  ((kind :initarg :kind :reader failure-kind)
   (detail :initarg :detail :reader failure-detail))
  (:report (lambda (c s) (format s "CHECK ~S: ~S" (failure-kind c) (failure-detail c)))))
(define-condition check-budget-exhausted (error) ()
  (:report (lambda (c s) (declare (ignorable c)) (write-string "CHECK assertion budget exhausted" s))))
(define-condition callback-fixture-error (error) ()
  (:report (lambda (c s) (declare (ignorable c)) (write-string "Original callback fixture error" s))))
(defstruct audit
  (remaining 200000) (assertions 0) (reads 0) (principal 0) (negative 0)
  (mutants 0) (ingress 0) (writer-rejections 0) (budget-rejections 0)
  (witnesses 0) (retry-budgets 0))
(defvar *audit* nil)

(defun demand (truth kind &rest detail)
  (unless (plusp (audit-remaining *audit*)) (error 'check-budget-exhausted))
  (decf (audit-remaining *audit*))
  (incf (audit-assertions *audit*))
  (unless truth (error 'check-failure :kind kind :detail detail))
  :checked)
(defun buffer ()
  (make-array 4 :element-type '(unsigned-byte 64)
              :initial-contents '(#xfedcba9876543210 #x8000000000000001
                                  #x1122334455667788 #xffffffffffffffff)))
(defun words-list (a) (coerce a 'list))
(defun unchanged (a before where)
  (demand (equalp a before) :destination-before-validation where (words-list a)))
(defun key (id)
  ;; Full 128-bit keys constructed here; no core generator or pattern oracle.
  (let ((a (make-array 16 :element-type '(unsigned-byte 8) :initial-element 0)))
    (cond ((zerop id) a)
          ((= id 1) (fill a 255))
          (t (dotimes (n 8 a)
               (setf (aref a n) (ldb (byte 8 (* 8 n)) id)
                     (aref a (+ n 8))
                     (ldb (byte 8 (* 8 n)) (logxor id #xd1b54a32d192ed03))))))))
(defun token (k) (coerce k 'list))
(defun tuple (words n)
  (let ((csn (mod (+ #x8000000000000001 (* n 104729)) (1+ +max64+)))
        (seg (mod (+ #xffffffff (* n 17)) #x100000000))
        (off (mod (+ #xfffffff1 (* n 43)) #x100000000))
        (len (mod (* n 65537) (1+ +max24+)))
        (end (if (= words 5) (mod (+ +max64+ (* n 97)) (1+ +max64+)) 0)))
    (list csn (+ (* seg #x100000000) off) len end)))
(defun store-tuple (i k data)
  (destructuring-bind (csn loc len end) data
    (arcdocdb.spk01:inserisci i k csn (floor loc #x100000000)
                            (mod loc #x100000000) len :end-csn end)))
(defstruct model
  (map (make-hash-table :test 'equal)) (journal nil) (puts 0) (deletes 0))
(defun model-put (i m k data)
  (multiple-value-bind (old present) (gethash (token k) (model-map m))
    (declare (ignorable old))
    (demand (eq (store-tuple i k data) (not present)) :writer-put)
    (setf (gethash (token k) (model-map m)) (copy-list data))
    (push (list :put (token k) (copy-list data)) (model-journal m))
    (incf (model-puts m))))
(defun model-delete (i m k)
  (multiple-value-bind (old present) (gethash (token k) (model-map m))
    (declare (ignorable old))
    (demand (eq (arcdocdb.spk01:elimina i k) present) :writer-delete)
    (remhash (token k) (model-map m))
    (push (list :delete (token k)) (model-journal m))
    (incf (model-deletes m))))
(defun replay-model (i m)
  (let ((replay (make-hash-table :test 'equal)))
    (dolist (event (reverse (model-journal m)))
      (ecase (first event)
        (:put (setf (gethash (second event) replay) (copy-list (third event))))
        (:delete (remhash (second event) replay))))
    (demand (= (hash-table-count replay) (hash-table-count (model-map m))) :replay-count)
    (maphash (lambda (k data)
               (demand (equal data (gethash k replay)) :replay-payload k)) (model-map m))
    (demand (= (hash-table-count replay) (arcdocdb.spk01::indice-documenti i)) :document-count)))

(defun baseline (i k d &key (attempts 8) after-fragment after-fields)
  (multiple-value-bind (csn loc len end status retries)
      (arcdocdb.spk01:leggi i k :attempts attempts
                              :after-fragment after-fragment :after-fields after-fields)
    (when (eq status :hit)
      (setf (aref d 0) csn (aref d 1) loc (aref d 2) len (aref d 3) end))
    (values status retries)))
(defun outcome (reader i k d expected retries &rest options)
  (let ((before (copy-seq d))
        (result (multiple-value-list (apply reader i k d options))))
    (demand (= (length result) 2) :return-arity (length result))
    (demand (and (keywordp (first result)) (typep (second result) 'fixnum)) :return-types)
    (demand (eq (first result) (if expected :hit :miss)) :status (first result))
    (demand (= (second result) retries) :retry-count (second result) retries)
    (if expected (demand (equal expected (words-list d)) :payload (words-list d) expected)
        (unchanged d before :miss))
    result))
(defun read-model (reader i m k)
  (let* ((expected (gethash (token k) (model-map m))) (a (buffer)) (b (buffer)))
    (let ((ra (outcome reader i k a expected 0))
          (rb (outcome #'baseline i k b expected 0)))
      (demand (and (equal ra rb) (equalp a b)) :baseline-comparison))
    (incf (audit-reads *audit*))))
(defun principal () (incf (audit-principal *audit*)))
(defun negative () (incf (audit-negative *audit*)))

(defun campaign (reader words)
  (let ((i (arcdocdb.spk01:make-indice :capacity 16 :words words :max-depth 16))
        (m (make-model)) (state 424242) (steps 0) (reads-before (audit-reads *audit*)))
    (dotimes (id 64)
      (model-put i m (key id) (tuple words (+ 1 id)))
      (read-model reader i m (key id)))
    (dotimes (block 128)
      (setf state (mod (+ (* state 1664525) 1013904223) #x100000000))
      (let ((k (key (mod (ash state -8) 64))) (n (+ 1000 (* block 3))))
        (model-put i m k (tuple words n)) (incf steps)
        (model-put i m k (tuple words (+ n 1))) (incf steps)
        (read-model reader i m k) (incf steps)
        (model-delete i m k) (incf steps)
        (read-model reader i m k) (incf steps)
        (model-put i m k (tuple words (+ n 2))) (incf steps)
        (read-model reader i m k) (incf steps)
        (read-model reader i m (key (+ 256 (mod (ash state -8) 64)))) (incf steps))
      (demand (= 64 (arcdocdb.spk01::indice-documenti i)) :campaign-population))
    (dotimes (id 384) (read-model reader i m (key id)))
    (replay-model i m)
    (demand (= steps 1024) :campaign-steps)
    (demand (= (model-puts m) 448) :campaign-puts)
    (demand (= (model-deletes m) 128) :campaign-deletes)
    (demand (= (length (model-journal m)) 576) :campaign-history)
    (demand (= (- (audit-reads *audit*) reads-before) 960) :campaign-reads)
    (demand (plusp (arcdocdb.spk01::indice-split i)) :campaign-split)
    (principal)
    (list :words words :seed 424242 :steps steps :blocks 128 :initial-puts 64
          :campaign-puts 384 :campaign-deletes 128 :campaign-reads 512
          :initial-reads 64 :final-reads 384 :read-comparisons 960
          :history-events 576 :final-live 64 :final-state state
          :splits (arcdocdb.spk01::indice-split i)
          :rebuilds (arcdocdb.spk01::indice-rebuild i))))

(defun boundaries (reader words)
  (let ((i (arcdocdb.spk01:make-indice :capacity 16 :words words)) (m (make-model))
        (values (list 0 1 most-positive-fixnum (1+ most-positive-fixnum)
                      #x8000000000000000 +max64+)))
    (loop for value in values for n from 0 do
      (let* ((loc (nth n (list 0 +max64+ most-positive-fixnum
                              (1+ most-positive-fixnum) #x8000000000000000 +max64+)))
             (data (list value loc (nth (mod n 3) (list 0 1 +max24+))
                         (if (= words 5) value 0))) (k (key n)))
        (model-put i m k data) (read-model reader i m k)
        (principal)))
    (model-delete i m (key 0)) (read-model reader i m (key 0))
    (model-delete i m (key 0)) (read-model reader i m (key 0))
    (model-put i m (key 0) (tuple words 999)) (read-model reader i m (key 0))
    (principal) (replay-model i m)
    (list :words words :records 6 :zero-key :covered :all-ff-key :covered
          :max64 +max64+ :length-max +max24+ :delete-absent :covered)))

(defun locate (i k)
  (let* ((h (arcdocdb.spk01::hash-chiave k 0))
         (f (arcdocdb.spk01::scegli-frammento (arcdocdb.spk01::indice-root i) h)))
    (multiple-value-bind (s present) (arcdocdb.spk01::cerca-writer f k h)
      (demand present :fixture-slot)
      (values f s))))
(defun rebuilds (reader words)
  (let ((i (arcdocdb.spk01:make-indice :capacity 16 :words words)) (m (make-model)))
    (dotimes (n 6) (model-put i m (key n) (tuple words n)))
    (dotimes (n 4) (model-delete i m (key n)))
    (demand (= (arcdocdb.spk01::indice-rebuild i) 0) :before-tombstone-rebuild)
    (model-put i m (key 10) (tuple words 10))
    (demand (= (arcdocdb.spk01::indice-rebuild i) 1) :tombstone-rebuild)
    (dotimes (n 12) (read-model reader i m (key n)))
    (multiple-value-bind (f s) (locate i (key 4))
      (setf (aref (arcdocdb.spk01::frammento-slots f)
                  (+ (* s words) 3)) (- arcdocdb.spk01::+soglia-seq+ 2)))
    (model-put i m (key 4) (tuple words 200))
    (demand (= (arcdocdb.spk01::indice-rebuild i) 2) :sequence-rebuild)
    (dotimes (n 12) (read-model reader i m (key n)))
    (replay-model i m) (principal)
    (list :words words :tombstone-rebuilds 1 :sequence-rebuilds 1)))

(defun collision-keys ()
  (let ((found nil) (count 0) (examined 0))
    (dotimes (n 131072)
      (let* ((k (key (+ n 2))) (h (arcdocdb.spk01::hash-chiave k 0)))
        (incf examined)
        (when (and (= 53 (logand h 127)) (= 15 (logand 15 (ash h -7))))
          (push k found) (incf count)
          (when (= count 7) (return)))))
    (demand (= count 7) :collision-search-budget count examined)
    (values (nreverse found) examined)))
(defun collision-trace (reader i k expected expected-slots)
  (let* ((d (buffer)) (before (copy-seq d)) (trace nil) (fragments 0))
    (outcome reader i k d expected 0
             :after-fragment (lambda (f)
                               (demand (arcdocdb.spk01::frammento-p f) :callback-fragment)
                               (incf fragments) (unchanged d before :collision-fragment))
             :after-fields (lambda (f s)
                             (demand (arcdocdb.spk01::frammento-p f) :callback-fields)
                             (push s trace) (unchanged d before :collision-fields)))
    (demand (= fragments 1) :callback-fragments)
    (demand (equal (reverse trace) expected-slots) :callback-trace (reverse trace) expected-slots)))
(defun collisions (reader words keys examined)
  (let ((i (arcdocdb.spk01:make-indice :capacity 16 :words words)) (m (make-model)))
    (loop for k in (subseq keys 0 6) for n from 0 do
      (model-put i m k (tuple words (+ 300 n)))
      (multiple-value-bind (f s) (locate i k)
        (declare (ignorable f))
        (demand (= s (mod (+ 15 n) 16)) :wrap-probe-placement)))
    (loop for k in keys for n from 0 do
      (let ((slots (subseq '(15 0 1 2 3 4) 0 (min 6 (1+ n))))
            (data (gethash (token k) (model-map m))))
        (collision-trace reader i k data slots)
        (collision-trace #'baseline i k data slots)
        (read-model reader i m k)))
    (model-delete i m (first keys))
    (read-model reader i m (sixth keys)) ; tombstone cannot terminate search
    (model-put i m (seventh keys) (tuple words 9999))
    (read-model reader i m (seventh keys))
    (multiple-value-bind (f s) (locate i (seventh keys))
      (declare (ignorable f)) (demand (= s 15) :wrap-tombstone-reuse))
    (replay-model i m) (principal)
    (list :words words :fingerprint 53 :probe-start 15 :occupied-slots '(15 0 1 2 3 4)
          :keys-found 7 :search-candidates examined :candidate-callbacks :verified)))

;;; Deterministic witnesses. Each invocation creates an independent index.
(defun witness (reader words mode)
  (let* ((i (arcdocdb.spk01:make-indice :capacity 8 :words words))
         (k (key 0)) (d (buffer)) (before (copy-seq d))
         (one (tuple words 1)) (two (tuple words 2)) (three (tuple words 3))
         (fc 0) (sc 0) (retired nil) (saved-odd nil)
         (expected three) (expected-status :hit) (expected-retries 1)
         (expected-fc 2) (expected-sc 2)
         (original (make-condition 'callback-fixture-error)))
    (unless (eq mode :root-miss) (store-tuple i k one))
    (case mode
      (:root-miss (setf expected-sc 1))
      (:fields-delete (setf expected nil expected-status :miss expected-sc 1))
      (:fields-odd (setf expected nil expected-status :retry-limit expected-retries 8
                         expected-fc 8 expected-sc 1))
      ((:root-churn :fields-churn)
       (setf expected nil expected-status :retry-limit expected-retries 8
             expected-fc 8 expected-sc 8))
      (:error-fragment (setf expected-fc 1 expected-sc 0))
      (:error-fields (setf expected-fc 1 expected-sc 1)))
    (labels ((fragment (f)
               (incf fc) (unchanged d before :after-fragment)
               (demand (arcdocdb.spk01::frammento-p f) :callback-fragment)
               (case mode
                 (:root-hit (when (= fc 1)
                              (store-tuple i k two)
                              (arcdocdb.spk01::manutenzione i f t)
                              (setf retired f) (store-tuple i k three)))
                 (:root-miss (when (= fc 1)
                               (arcdocdb.spk01::manutenzione i f nil)
                               (setf retired f) (store-tuple i k three)))
                 (:root-churn (arcdocdb.spk01::manutenzione i f nil))
                 (:error-fragment (error original)))
               (unchanged d before :after-fragment-writer))
             (fields (f s)
               (incf sc) (unchanged d before :after-fields)
               (demand (and (arcdocdb.spk01::frammento-p f) (typep s 'fixnum)
                            (<= 0 s) (< s 8)) :callback-slot)
               (case mode
                 (:fields-update (when (= sc 1) (store-tuple i k three)))
                 (:fields-delete (when (= sc 1) (arcdocdb.spk01:elimina i k)))
                 (:fields-odd
                  (let* ((slots (arcdocdb.spk01::frammento-slots f))
                         (position (+ (* s words) 3)) (seq (aref slots position)))
                    (setf saved-odd (list slots position seq)
                          (aref slots position) (1+ seq))))
                 (:fields-churn (store-tuple i k (tuple words (+ sc 20))))
                 (:error-fields (error original)))
               (unchanged d before :after-fields-writer)))
      (unwind-protect
           (if (member mode '(:error-fragment :error-fields))
               (let ((caught (handler-case
                                 (progn (funcall reader i k d :after-fragment #'fragment
                                                :after-fields #'fields) nil)
                               (error (c) c))))
                 (demand (eq caught original) :callback-original-error)
                 (unchanged d before :callback-error))
               (let ((result (multiple-value-list
                              (funcall reader i k d :after-fragment #'fragment
                                       :after-fields #'fields))))
                 (demand (= (length result) 2) :return-arity)
                 (demand (eq (first result) expected-status) :status (first result) expected-status)
                 (demand (typep (second result) 'fixnum) :return-types)
                 (demand (= (second result) expected-retries) :retry-count)
                 (if expected (demand (equal expected (words-list d)) :payload)
                     (unchanged d before :non-hit))))
        (when saved-odd
          (setf (aref (first saved-odd) (second saved-odd)) (third saved-odd)))))
    (demand (= fc expected-fc) :fragment-callback-count fc expected-fc)
    (demand (= sc expected-sc) :fields-callback-count sc expected-sc)
    (when retired
      (multiple-value-bind (csn loc len end status)
          (arcdocdb.spk01::sonda-reader retired k (arcdocdb.spk01::hash-chiave k 0) nil)
        (demand (eq status (if (eq mode :root-hit) :hit :miss)) :retired-status)
        (when (eq mode :root-hit)
          (demand (equal (list csn loc len end) two) :retired-payload))))
    (list :case mode :words words :status (if (member mode '(:error-fragment :error-fields))
                                             :original-error expected-status)
          :retries (if (member mode '(:error-fragment :error-fields)) :not-returned expected-retries)
          :fragment-callbacks fc :fields-callbacks sc :buffer-publication :validated)))
(defun witnesses (reader words)
  (loop for mode in '(:root-hit :root-miss :fields-update :fields-delete :fields-odd
                     :root-churn :fields-churn :error-fragment :error-fields)
        collect (let ((a (witness reader words mode)) (b (witness #'baseline words mode)))
                  (demand (equal a b) :witness-baseline mode)
                  (incf (audit-witnesses *audit*)) (principal) a)))

(defun retry-budgets (reader words)
  (let* ((i (arcdocdb.spk01:make-indice :capacity 8 :words words)) (k (key 0)))
    (store-tuple i k (tuple words 1))
    (multiple-value-bind (f s) (locate i k)
      (let* ((slots (arcdocdb.spk01::frammento-slots f)) (pos (+ (* s words) 3))
             (seq (aref slots pos)))
        (setf (aref slots pos) (1+ seq))
        (unwind-protect
             (loop for attempts from 1 to 8 do
               (dolist (r (list reader #'baseline))
                 (let* ((d (buffer)) (before (copy-seq d)) (fc 0) (sc 0)
                        (result (multiple-value-list
                                 (funcall r i k d :attempts attempts
                                          :after-fragment (lambda (fragment)
                                                            (demand (eq fragment f) :odd-fragment)
                                                            (incf fc) (unchanged d before :odd-fragment))
                                          :after-fields (lambda (fragment slot)
                                                          (declare (ignorable fragment slot)) (incf sc))))))
                   (demand (equal result (list :retry-limit attempts)) :odd-retry-limit)
                   (demand (= fc attempts) :odd-all-attempts)
                   (demand (zerop sc) :odd-no-fields)
                   (unchanged d before :odd-budget)))
               (principal) (incf (audit-retry-budgets *audit*)))
          (setf (aref slots pos) seq))))
    (list :words words :attempts '(1 2 3 4 5 6 7 8) :status :retry-limit)))

;;; Local mutant implementation. Never installed into core/kernel symbol-functions.
(defun mutant-slot (mode f s k h d after-fields)
  (let* ((slots (arcdocdb.spk01::frammento-slots f))
         (width (arcdocdb.spk01::frammento-larghezza f)) (base (* s width))
         (seq (aref slots (+ base 3))))
    (when (and (not (eq mode :no-seqlock)) (oddp seq))
      (return-from mutant-slot (values 0 0 0 0 :retry)))
    (sb-thread:barrier (:read))
    (let* ((csn (aref slots base)) (loc (aref slots (+ base 1)))
           (meta (aref slots (+ base 2))) (end (if (= width 5) (aref slots (+ base 4)) 0))
           (arena (arcdocdb.spk01::frammento-chiavi f)) (off (ldb (byte 24 0) meta))
           (match (and (= (aref (arcdocdb.spk01::frammento-ctrl f) s) (logand 127 h))
                       (= 1 (ldb (byte 8 56) meta)) (= 16 (ldb (byte 8 24) meta))
                       (<= (+ off 16) (length arena))
                       (arcdocdb.spk01::stessa-chiave-p k arena off))))
      (when (and match (eq mode :early-destination))
        (setf (aref d 0) csn (aref d 1) loc (aref d 2) (ldb (byte 24 32) meta) (aref d 3) end))
      (when after-fields (funcall after-fields f s))
      (sb-thread:barrier (:read))
      (if (and (not (eq mode :no-seqlock)) (/= seq (aref slots (+ base 3))))
          (values 0 0 0 0 :retry)
          (values csn loc (ldb (byte 24 32) meta) end (if match :hit :skip))))))
(defun mutant-probe (mode f k h d after-fields)
  (dotimes (n (arcdocdb.spk01::frammento-capacita f) (values 0 0 0 0 :miss))
    (let* ((s (arcdocdb.spk01::posizione-sonda h (arcdocdb.spk01::frammento-capacita f) n))
           (ctrl (aref (arcdocdb.spk01::frammento-ctrl f) s)))
      (when (= ctrl 255) (return-from mutant-probe (values 0 0 0 0 :miss)))
      (when (= ctrl (logand h 127))
        (multiple-value-bind (csn loc len end status) (mutant-slot mode f s k h d after-fields)
          (unless (eq status :skip)
            (return-from mutant-probe (values csn loc len end status))))))))
(defun mutant (mode)
  (lambda (i k d &key (attempts 8) after-fragment after-fields)
    (let ((h (arcdocdb.spk01::hash-chiave k 0)))
      (block reading
        (dotimes (attempt attempts (values :retry-limit attempts))
          (let* ((root (arcdocdb.spk01::indice-root i))
                 (gen (arcdocdb.spk01::radice-generazione root)))
            (sb-thread:barrier (:read))
            (let ((f (arcdocdb.spk01::scegli-frammento root h)))
              (when after-fragment (funcall after-fragment f))
              (multiple-value-bind (csn loc len end status) (mutant-probe mode f k h d after-fields)
                (sb-thread:barrier (:read))
                (let ((actual (arcdocdb.spk01::indice-root i)))
                  (when (and (not (eq status :retry))
                             (or (eq mode :no-root)
                                 (and (eq root actual) (= gen (arcdocdb.spk01::radice-generazione actual)))))
                    (when (eq status :hit)
                      (let ((data (list csn loc len end)))
                        (when (eq mode :truncate-u64)
                          (setf data (mapcar (lambda (word) (logand word most-positive-fixnum)) data)))
                        (replace d data)))
                    (return-from reading (values status attempt))))))))))))
(defun mutant-rejections (words)
  (loop for (mode test kinds) in
        '((:no-root :root-hit (:retry-count :payload))
          (:no-root :root-miss (:status))
          (:no-seqlock :fields-update (:retry-count :payload))
          (:no-seqlock :fields-delete (:status))
          (:no-seqlock :fields-odd (:status))
          (:truncate-u64 :boundary (:payload))
          (:early-destination :fields-update (:destination-before-validation))
          (:early-destination :fields-delete (:destination-before-validation)))
        collect
        (let ((c (handler-case
                     (progn
                       (if (eq test :boundary)
                           (let* ((i (arcdocdb.spk01:make-indice :capacity 8 :words words))
                                  (k (key 1)) (data (list +max64+ +max64+ +max24+
                                                         (if (= words 5) +max64+ 0))))
                             (store-tuple i k data) (outcome (mutant mode) i k (buffer) data 0))
                           (witness (mutant mode) words test))
                       nil)
                   (check-failure (failure) failure))))
          (demand (and c (member (failure-kind c) kinds)) :mutant-not-rejected mode test)
          (negative) (incf (audit-mutants *audit*))
          (list :mutation mode :witness test :rejected-by (failure-kind c)))))

(defun reject-input (reader i k d options backing)
  (let* ((watched (and (arrayp d) d))
         (before (when watched (copy-seq watched)))
         (backing-before (when backing (copy-seq backing)))
         (key-before (when (arrayp k) (copy-seq k)))
         (caught (handler-case (progn (apply reader i k d options) nil) (error (c) c))))
    (demand (and caught (or (typep caught 'type-error) (typep caught 'program-error)
                           (typep caught 'arcdocdb.spk01:limite-indice))) :input-not-rejected)
    (when watched (unchanged watched before :invalid-input))
    (when backing (unchanged backing backing-before :invalid-input-backing))
    (when key-before (demand (equalp k key-before) :invalid-key-mutated))
    (negative) (incf (audit-ingress *audit*))
    (list :rejection-type (string (type-of caught)) :destination :unchanged)))
(defun ingress (reader words)
  (let* ((i (arcdocdb.spk01:make-indice :capacity 8 :words words)) (k (key 0))
         (backing (make-array 8 :element-type '(unsigned-byte 64) :initial-element 111))
         (cases nil))
    (store-tuple i k (tuple words 1))
    (push (list :index (reject-input reader nil k (buffer) nil nil)) cases)
    (dolist (bad-key (list nil #(0 0 0 0) (make-array 15 :element-type '(unsigned-byte 8))
                          (make-array 17 :element-type '(unsigned-byte 8))
                          (make-array 16 :element-type '(unsigned-byte 8) :adjustable t)
                          (make-array 16 :element-type '(unsigned-byte 16))))
      (push (list :key (reject-input reader i bad-key (buffer) nil nil)) cases))
    (dolist (bad-dest (list nil #(1 2 3 4)
                           (make-array 3 :element-type '(unsigned-byte 64))
                           (make-array 5 :element-type '(unsigned-byte 64))
                           (make-array 4 :element-type '(unsigned-byte 32))
                           (make-array 4 :element-type '(unsigned-byte 64) :adjustable t)
                           (make-array 4 :element-type '(unsigned-byte 64) :fill-pointer 4)
                           (make-array 4 :element-type '(unsigned-byte 64)
                                       :displaced-to backing :displaced-index-offset 2)))
      (push (list :destination (reject-input reader i k bad-dest nil backing)) cases))
    (dolist (bad-attempts '(0 9 -1 1.0 "8"))
      (push (list :attempts (reject-input reader i k (buffer) (list :attempts bad-attempts) nil)) cases))
    (dolist (name '(:after-fragment :after-fields))
      (push (list name (reject-input reader i k (buffer) (list name 42) nil)) cases))
    (push (list :unknown-keyword (reject-input reader i k (buffer) '(:unknown 1) nil)) cases)
    (demand (= (length cases) 23) :ingress-count)
    (list :words words :cases 23 :rejections (nreverse cases))))

(defun writer-rejections (reader words)
  (let* ((i (arcdocdb.spk01:make-indice :capacity 8 :words words)) (k (key 0))
         (data (tuple words 1)) (m (make-model)) (count 0))
    (model-put i m k data)
    (dolist (bad (list (list (1+ +max64+) 0 0 0 0)
                      (list 1 #x100000000 0 0 0) (list 1 0 #x100000000 0 0)
                      (list 1 0 0 (1+ +max24+) 0) (list 1 0 0 0 (1+ +max64+))
                      (list 1 0 0 0 (if (= words 4) 1 -1))))
      (let* ((d (buffer)) (before (copy-seq d))
             (caught (handler-case
                         (progn (destructuring-bind (csn seg off len end) bad
                                  (arcdocdb.spk01:inserisci i k csn seg off len :end-csn end)) nil)
                       (error (c) c))))
        (demand (and caught (or (typep caught 'type-error)
                               (typep caught 'arcdocdb.spk01:limite-indice))) :writer-not-rejected)
        (unchanged d before :writer-error)
        (read-model reader i m k) (negative) (incf count)
        (incf (audit-writer-rejections *audit*))))
    (demand (= count 6) :writer-rejection-count)
    (list :words words :cases count :original-record :preserved)))
(defun writer-budgets (reader words)
  (let ((i (arcdocdb.spk01:make-indice :capacity 8 :words words :max-depth 0))
        (m (make-model)))
    (dotimes (id 7) (model-put i m (key id) (tuple words (+ 1 id))))
    (let* ((d (buffer)) (before (copy-seq d))
           (caught (handler-case (progn (store-tuple i (key 7) (tuple words 99)) nil)
                     (arcdocdb.spk01:limite-indice (c) c))))
      (demand (and caught (eq (arcdocdb.spk01::limite-motivo caught) :profondita-directory))
              :depth-budget-not-rejected)
      (unchanged d before :depth-budget)
      (dotimes (id 8) (read-model reader i m (key id)))
      (replay-model i m) (negative) (incf (audit-writer-rejections *audit*)))
    (let ((caught (handler-case
                      (progn (arcdocdb.spk01:make-indice :capacity 32768 :words words :memory-mib 1) nil)
                    (arcdocdb.spk01:limite-indice (c) c))))
      (demand (and caught (eq (arcdocdb.spk01::limite-motivo caught) :payload-iniziale))
              :memory-budget-not-rejected)
      (negative) (incf (audit-writer-rejections *audit*)))
    (list :words words :depth-budget :explicit-error :memory-budget :explicit-error
          :partial-success :false :preserved-records 7)))
(defun budget-rejection ()
  (let ((caught (handler-case
                    (progn (check :budget 0) nil)
                  (check-budget-exhausted (c) c))))
    (demand (typep caught 'check-budget-exhausted) :budget-not-rejected)
    (negative) (incf (audit-budget-rejections *audit*))
    (list :status :explicit-error :condition-type "CHECK-BUDGET-EXHAUSTED")))

(defun portable-data-p (x)
  (typecase x
    (null t) (cons (and (portable-data-p (car x)) (portable-data-p (cdr x))))
    (string t) (number t) (symbol (keywordp x)) (t nil)))
(defun check (&key (budget 200000))
  "Finite independent-model CHECK; no BENCH, no thread/scheduler assumptions."
  (unless (typep budget '(integer 0 200000))
    (error 'type-error :datum budget :expected-type '(integer 0 200000)))
  (let* ((*audit* (make-audit :remaining budget))
         (package (or (find-package "ARCDOCDB.SPK01.LETTURA-BUFFER")
                      (error "Kernel package absent; CHECK not attempted")))
         (symbol (find-symbol "LEGGI" package))
         (reader (and symbol (fboundp symbol) (symbol-function symbol))))
    (demand reader :kernel-function)
    (multiple-value-bind (keys examined) (collision-keys)
      (let ((campaigns nil) (boundary-reports nil) (rebuild-reports nil)
            (collision-reports nil) (witness-reports nil) (retry-reports nil)
            (ingress-reports nil) (writer-reports nil) (writer-budget-reports nil)
            (mutation-reports nil))
        (dolist (words '(4 5))
          (push (campaign reader words) campaigns)
          (push (boundaries reader words) boundary-reports)
          (push (rebuilds reader words) rebuild-reports)
          (push (collisions reader words keys examined) collision-reports)
          (push (list :words words :cases (witnesses reader words)) witness-reports)
          (push (retry-budgets reader words) retry-reports)
          (push (ingress reader words) ingress-reports)
          (push (writer-rejections reader words) writer-reports)
          (push (writer-budgets reader words) writer-budget-reports)
          (push (list :words words :cases (mutant-rejections words)) mutation-reports))
        (let ((exhaustion (budget-rejection)))
          (demand (= (audit-reads *audit*) 2032) :total-model-reads)
          (demand (= (audit-principal *audit*) 54) :total-principal)
          (demand (= (audit-negative *audit*) 79) :total-negative)
          (demand (= (audit-ingress *audit*) 46) :total-ingress)
          (demand (= (audit-writer-rejections *audit*) 16) :total-writer-rejections)
          (demand (= (audit-budget-rejections *audit*) 1) :total-budget-rejections)
          (demand (= (audit-mutants *audit*) 16) :total-mutants)
          (demand (= (audit-witnesses *audit*) 18) :total-witnesses)
          (demand (= (audit-retry-budgets *audit*) 16) :total-retry-budgets)
          (let ((report
                  (list :schema-version 1 :status :ok :spike :spk-01 :phase 0
                        :layout :v1 :layouts '(:words4 :words5-extra-end)
                        :verifies-format-v2 :false :safety 3 :bench-executed :false
                        :kernel "ARCDOCDB.SPK01.LETTURA-BUFFER:LEGGI"
                        :baseline "ARCDOCDB.SPK01:LEGGI"
                        :model :independent-map-with-journal-replay
                        :principal-cases (audit-principal *audit*)
                        :negative-controls (audit-negative *audit*)
                        :negative-counts (list :ingress 46 :writer 16 :budget 1 :mutants 16)
                        :read-comparisons (audit-reads *audit*)
                        :campaigns (nreverse campaigns) :boundaries (nreverse boundary-reports)
                        :rebuilds (nreverse rebuild-reports) :collisions (nreverse collision-reports)
                        :witnesses (nreverse witness-reports) :retry-budgets (nreverse retry-reports)
                        :invalid-inputs (nreverse ingress-reports)
                        :writer-rejections (nreverse writer-reports)
                        :writer-budgets (nreverse writer-budget-reports)
                        :mutants (nreverse mutation-reports) :budget-exhaustion exhaustion
                        :budget (list :maximum budget :remaining (audit-remaining *audit*)
                                      :assertions (audit-assertions *audit*))
                        :limitations '(:finite-campaign :synchronous-interleavings
                                       :no-hardware-memory-model-proof :no-thread-stress))))
            (demand (portable-data-p report) :foreign-symbol-in-report)
            (setf (getf report :budget)
                  (list :maximum budget :remaining (audit-remaining *audit*)
                        :assertions (audit-assertions *audit*)))
            report))))))
