;;;; Launcher C4 indipendente dalla cwd. Stdout contiene una sola plist.
(in-package #:cl-user)
(declaim (optimize (safety 3) (speed 2) (debug 1)))

(defun spk01-opzioni (args)
  (let ((mode :bench) (options nil))
    (when (and args (member (first args) '("--check" "--bench") :test #'string=))
      (setf mode (if (string= (pop args) "--check") :check :bench)))
    (when (and (eq mode :check) args) (error "--check non accetta opzioni benchmark."))
    (loop repeat (ceiling (length args) 2) do
      (let* ((name (pop args)) (value (pop args))
             (key (cdr (assoc name '(("--documents" . :documents) ("--seconds" . :seconds)
                                    ("--capacity" . :capacity) ("--words" . :words)
                                    ("--readers" . :readers) ("--memory-mib" . :memory-mib))
                             :test #'string=))))
        (unless (and key value (plusp (length value)) (every #'digit-char-p value))
          (error "Opzione SPK-01 non valida: ~S ~S" name value))
        (when (member key options) (error "Opzione duplicata: ~A" name))
        (setf options (append options (list key (parse-integer value :junk-allowed nil))))))
    (values mode options)))

(defun spk01-main ()
  (let* ((base (make-pathname :name nil :type nil :defaults *load-truename*))
         (source (merge-pathnames "core.lisp" base))
         (fasl (merge-pathnames "out/core.fasl" base)))
    (ensure-directories-exist fasl)
    (handler-bind ((warning (lambda (c) (error "Compilazione SPK-01: ~A" c)))
                   (style-warning (lambda (c) (error "Compilazione SPK-01: ~A" c))))
      (multiple-value-bind (output warnings failure)
          (compile-file source :output-file fasl :verbose nil :print nil)
        (when (or warnings failure (null output)) (error "Compilazione SPK-01 fallita."))
        (load output :verbose nil :print nil)))
    (multiple-value-bind (mode options) (spk01-opzioni (rest sb-ext:*posix-argv*))
      (let* ((package (or (find-package "ARCDOCDB.SPK01") (error "Package SPK-01 assente.")))
             (check (symbol-function (or (find-symbol "CHECK" package) (error "CHECK assente."))))
             (benchmark (symbol-function (or (find-symbol "BENCHMARK" package)
                                            (error "BENCHMARK assente."))))
             (verification (funcall check)))
        (if (eq mode :check) verification
            (list :spike :spk-01 :check verification :benchmark (apply benchmark options)))))))

(let ((*read-eval* nil) (*print-readably* nil) (*print-escape* t) (*print-pretty* t))
  (handler-case (progn (write (spk01-main)) (terpri) (finish-output))
    (error (c)
      (write (list :spike :spk-01 :status :error :condition (princ-to-string c)))
      (terpri) (finish-output) (sb-ext:exit :code 1))))
