;;;; Misura formazione/SEAL e gruppo I/O simulato; nessuna prestazione del database.
;;; REQ: REQ-WAL-002 REQ-WAL-005 REQ-VAL-001
(require :asdf)
(asdf:load-asd (merge-pathnames "arcdocdb.asd" (truename "./")))
(asdf:load-system "arcdocdb")
(declaim (optimize (safety 3) (speed 2) (debug 2)))
(defun bench-buffer (n) (make-array n :element-type '(unsigned-byte 8) :initial-element 42))
(defun bench-sample (fn iterations)
  (dotimes (i 1024) (funcall fn)) (sb-ext:gc :full t)
  (let ((before (sb-ext:get-bytes-consed)) (start (get-internal-real-time)) (sink 0))
    (declare (type fixnum sink))
    (dotimes (i iterations) (setf sink (logxor sink (the fixnum (funcall fn)))))
    (let ((heap (- (sb-ext:get-bytes-consed) before))
          (seconds (/ (- (get-internal-real-time) start) (float internal-time-units-per-second 1d0))))
      (list :iterations iterations :heap-bytes heap :seconds seconds :sink sink
            :operations-per-second (and (plusp seconds) (/ iterations seconds))))))
(defun bench-self-test ()
  (let ((probe nil))
    (unless (zerop (getf (bench-sample (lambda () 42) 4096) :heap-bytes))
      (error "COD-60: baseline non zero."))
    (unless (plusp (getf (bench-sample (lambda () (setf probe (bench-buffer 64)) (length probe)) 4096)
                        :heap-bytes)) (error "COD-60: allocazioni deliberate non rilevate.")))
  (write '(:self-test :ok)) (terpri))
(defun bench-campaign (name stamp file-id)
  (let* ((key (bench-buffer 16)) (value (bench-buffer 2048))
         (lotto (arcdocdb.wal:crea-lotto :segment file-id :capacity 65536 :max-records 32))
         (backend (arcdocdb.io:make-backend
                    (lambda (name mode) (declare (ignore name mode)) 7)
                    (lambda (&rest args) (error "Read inattesa: ~S" args))
                    (lambda (fd b start count) (declare (ignore fd b start)) count)
                    (lambda (fd) (declare (ignore fd)) 0)
                    (lambda (&rest args) (error "Directory inattesa: ~S" args))
                    (lambda (fd) (declare (ignore fd)) 0)))
         (file (arcdocdb.io:crea-temporaneo "bench.tmp" :backend backend :max-file-bytes most-positive-fixnum))
         (log (arcdocdb.wal:crea-log-io file :segment file-id))
         (group (arcdocdb.wal:crea-gruppo log :max-lots 1))
         (fn (lambda ()
               (dotimes (i 8) (arcdocdb.wal:aggiungi-record lotto 1 key value))
               (arcdocdb.wal:sigilla-lotto lotto stamp (arcdocdb.io:posizione-scritta file)
                                         (arcdocdb.io:posizione-durevole file))
               (arcdocdb.wal:aggiungi-lotto group lotto) (arcdocdb.wal:chiudi-gruppo group)
               (arcdocdb.wal:esegui-gruppo group)
               (arcdocdb.wal:riusa-gruppo group) (arcdocdb.wal:riusa-lotto lotto) 8)))
    (unwind-protect (list :name name :records-per-group 8 :value-bytes 2048
                         :samples (loop repeat 5 collect (bench-sample fn 8192)))
      (arcdocdb.io:chiudi file))))
(defun bench-run ()
  (let ((campaigns (list (bench-campaign :normal-csn 19 31)
                        (bench-campaign :u64-limit-csn-and-file #xffffffffffffffff #xffffffffffffffff))))
    (write (list :scope :wal-build-and-simulated-group :safety 3 :workers 1 :recorded-at (get-universal-time)
                 :timer-units-per-second internal-time-units-per-second :campaigns campaigns
                 :limits '(:simulated-write-and-flush :not-request-latency :no-index-publication
                           :not-database-throughput :external-load-uncontrolled)) :pretty t)
    (terpri)
    (unless (every (lambda (c) (every (lambda (s) (zerop (getf s :heap-bytes))) (getf c :samples))) campaigns)
      (error "COD-30: allocazioni rilevate; risultati conservati nell'output."))))
(let ((args (uiop:command-line-arguments)))
  (cond ((equal args '("--self-test")) (bench-self-test))
        ((equal args '("--bench")) (bench-run))
        (t (error "Usare --self-test o --bench."))))
