;;;; Confronto SIMD in uno spike, non nel motore.
;;; REQ: REQ-SIM-001 REQ-SIM-002 REQ-VAL-001
(defpackage #:arcdocdb.spk08.simd (:use #:cl) (:export #:check #:bench))
(in-package #:arcdocdb.spk08.simd)
(declaim (optimize (safety 3) (speed 3) (debug 1)))
(deftype octets () '(simple-array (unsigned-byte 8) (*)))

(define-condition gruppo-invalido (error)
  ((motivo :initarg :motivo :reader motivo))
  (:report (lambda (c s) (format s "Gruppo SIMD non valido: ~S." (motivo c)))))

(defun backend ()
  #+arm64 (sb-simd-internals:instruction-set-case (:neon :neon) (() :unsupported))
  #+x86-64 (sb-simd-internals:instruction-set-case (:sse2 :sse2) (() :unsupported))
  #-(or arm64 x86-64) :unsupported)

(declaim (inline controlla-gruppo comprimi-bit-alti maschera-scalare maschera-simd))
(defun controlla-gruppo (buffer offset query)
  (declare (type octets buffer) (type fixnum offset) (type (unsigned-byte 8) query))
  (unless (and (<= 0 offset (- (length buffer) 16)) (< query 128))
    (error 'gruppo-invalido :motivo (list :offset offset :length (length buffer) :query query)))
  nil)

(defun comprimi-bit-alti (word)
  "Compressione esatta: bit 7+8*i -> bit i; prodotto ridotto modulo 2^64."
  (declare (type (unsigned-byte 64) word))
  (ldb (byte 8 56)
       (ldb (byte 64 0)
            (* (ash (logand word #x8080808080808080) -7) #x0102040810204080))))

(defun maschera-scalare (buffer offset query)
  (declare (type octets buffer) (type fixnum offset) (type (unsigned-byte 8) query))
  (controlla-gruppo buffer offset query)
  (let ((mask 0))
    (declare (type (unsigned-byte 16) mask))
    (dotimes (i 16 mask)
      (when (= (aref buffer (+ offset i)) query) (setf mask (logior mask (ash 1 i)))))))

(defun maschera-simd (buffer offset query)
  (declare (type octets buffer) (type fixnum offset) (type (unsigned-byte 8) query))
  (controlla-gruppo buffer offset query)
  #+arm64
  (multiple-value-bind (low high)
      (sb-simd-neon:u64.2-values
       (sb-simd-neon:u64.2!
        (sb-simd-neon:u8.16= (sb-simd-neon:u8.16-aref buffer offset)
                             (sb-simd-neon:u8.16-broadcast query))))
    (logior (comprimi-bit-alti low) (ash (comprimi-bit-alti high) 8)))
  #+x86-64
  (sb-simd-sse2:u8.16-movemask
   (sb-simd-sse2:u8.16= (sb-simd-sse2:u8.16-aref buffer offset)
                        (sb-simd-sse2:u8.16-broadcast query)))
  #-(or arm64 x86-64) (error 'gruppo-invalido :motivo :unsupported))

(defun check ()
  (when (eq (backend) :unsupported)
    (return-from check (list :status :unsupported :module :simd :reason :instruction-set)))
  (let ((buffer (make-array 64 :element-type '(unsigned-byte 8) :initial-element 128))
        (count 0) (immutati 0) (rifiuti 0))
    (labels ((confronta (offset query expected)
               (incf count)
               (when (> count 600000) (error 'gruppo-invalido :motivo :case-budget))
               (unless (= expected (maschera-scalare buffer offset query)
                                   (maschera-simd buffer offset query))
                 (error 'gruppo-invalido :motivo (list :oracle count offset query expected)))))
      (dotimes (mask 65536)
        (let ((offset (+ 8 (mod mask 16))))
          (dotimes (i 16) (setf (aref buffer (+ offset i)) (if (logbitp i mask) 17 128)))
          (confronta offset 17 mask)))
      (fill buffer 128)
      (dotimes (query 128)
        (dotimes (value 256)
          (dotimes (lane 16)
            (let ((offset (+ 8 (mod (+ query lane) 16))))
              (setf (aref buffer (+ offset lane)) value)
              (confronta offset query (if (= value query) (ash 1 lane) 0))
              (setf (aref buffer (+ offset lane)) 128)))))
      (dotimes (offset 16)
        (let ((before (copy-seq buffer)))
          (maschera-simd buffer offset 42)
          (unless (equalp buffer before) (error 'gruppo-invalido :motivo :input-modified))
          (incf immutati)))
      (dolist (args (list (list buffer -1 42) (list buffer 49 42) (list buffer 0 128)
                         (list (make-array 15 :element-type '(unsigned-byte 8)) 0 42)))
        (let ((before (copy-seq (first args))) (rejected nil))
          (handler-case (apply #'maschera-simd args)
            (gruppo-invalido () (setf rejected t)))
          (unless (and rejected (equalp before (first args)))
            (error 'gruppo-invalido :motivo :invalid-argument-control))
          (incf rifiuti))))
    (list :status :ok :module :simd :backend (backend) :comparisons count
          :immutable-input-cases immutati :rejected-arguments rifiuti
          :budget 600000 :alignment-offsets '(8 23)
          :disassembly (with-output-to-string (*standard-output*) (disassemble #'maschera-simd))
          :limits '(:one-immutable-group :no-index :no-seqlock :local-backend-only))))

(macrolet ((definisci-ciclo (name kernel)
             `(defun ,name (buffer rounds)
                (declare (type octets buffer) (type (integer 1 256) rounds))
                (let ((sum 0) (groups (ash (length buffer) -4)))
                  (declare (type (unsigned-byte 32) sum) (type fixnum groups))
                  (dotimes (round rounds sum)
                    (dotimes (group groups)
                      (setf sum (ldb (byte 32 0)
                                     (+ sum (,kernel buffer (ash group 4) 42))))))))))
  (definisci-ciclo ciclo-scalare maschera-scalare)
  (definisci-ciclo ciclo-simd maschera-simd))

(defun prepara-dataset (kind)
  (let ((buffer (make-array (* 16384 16) :element-type '(unsigned-byte 8))))
    (dotimes (group 16384 buffer)
      (dotimes (lane 16)
        (setf (aref buffer (+ (* group 16) lane))
              (ecase kind
                (:mixed (mod (+ (* 17 group) (* 7 lane)) 256))
                (:all-hit 42)
                (:special-no-hit (if (evenp lane) 128 254))))))))

(defun campione (method buffer replica)
  "Solo ciclo fra i contatori; non include report, warmup, fixture o GC."
  (sb-ext:gc :full t)
  (let* ((before (sb-ext:get-bytes-consed)) (start (get-internal-real-time))
         (sum (ecase method (:scalar (ciclo-scalare buffer 256)) (:simd (ciclo-simd buffer 256))))
         (ticks (- (get-internal-real-time) start))
         (bytes (- (sb-ext:get-bytes-consed) before))
         (operations (* 16384 256))
         (seconds (/ (coerce ticks 'double-float) internal-time-units-per-second)))
    (unless (plusp ticks) (error 'gruppo-invalido :motivo :timer-resolution))
    (list :method method :replica replica :operations operations :sum sum
          :ticks ticks :timer-units internal-time-units-per-second :seconds seconds
          :ns-per-group (/ (* seconds 1d9) operations)
          :bytes-consed bytes :bytes-per-group (/ (coerce bytes 'double-float) operations))))

(defun controllo-contatore ()
  (let* ((before (sb-ext:get-bytes-consed))
         (buffer (make-array 131072 :element-type '(unsigned-byte 8) :initial-element 91))
         (observed (aref buffer 131071)) (bytes (- (sb-ext:get-bytes-consed) before)))
    (unless (and (= observed 91) (plusp bytes))
      (error 'gruppo-invalido :motivo :allocation-sensor))
    (list :allocated-array-bytes 131072 :observed-bytes-consed bytes :sentinel observed)))

(defun bench ()
  (let ((verified (check)))
    (when (eq (getf verified :status) :unsupported) (return-from bench verified))
    (let ((measurements nil) (sensor (controllo-contatore)))
      (dolist (kind '(:mixed :all-hit :special-no-hit))
        (let* ((buffer (prepara-dataset kind)) (expected (ciclo-scalare buffer 256)))
          (unless (= expected (ciclo-simd buffer 256))
            (error 'gruppo-invalido :motivo :warmup-mismatch))
          (dotimes (replica 5)
            (dolist (method (if (evenp replica) '(:scalar :simd) '(:simd :scalar)))
              (let ((sample (campione method buffer replica)))
                (unless (= expected (getf sample :sum))
                  (error 'gruppo-invalido :motivo :measured-result-mismatch))
                (push (list :dataset kind :sample sample) measurements))))))
      (list :status :measured :module :simd :backend (backend)
            :groups 16384 :rounds 256 :replicas 5 :query 42 :group-bytes 16
            :allocation-sensor sensor :measurements (nreverse measurements)
            :limits '(:cache-resident-synthetic-data :no-db-throughput
                      :uncontrolled-external-load :single-worker :local-backend-only)))))
